<?php
if (!defined('ABSPATH')) exit;

/** Student-selected Canvas submission and teacher-approved AGS grade passback. */
final class MathBinder_Canvas_Submission {
    const LAUNCH_PREFIX = 'mb_canvas_submission_launch_';

    public static function register() {
        add_action('template_redirect', [__CLASS__, 'route_pages'], 1);
        add_action('admin_post_nopriv_mathbinder_canvas_submit_notes', [__CLASS__, 'submit_notes']);
        add_action('admin_post_mathbinder_canvas_submit_notes', [__CLASS__, 'submit_notes']);
        add_action('admin_post_mb_teacher_canvas_send_grade', [__CLASS__, 'send_grade']);
        add_action('admin_post_mathbinder_canvas_approve_mapping', [__CLASS__, 'approve_mapping']);
    }

    public static function begin_launch(array $result) {
        if (($result['message_type'] ?? '') !== 'LtiDeepLinkingRequest' || !self::is_learner((array)($result['roles'] ?? []))) return null;
        $claims=(array)$result['claims']; $external_user=(string)($claims['sub'] ?? ''); $context=(array)($result['context']??[]); $settings=MathBinder_Canvas_Settings::get();
        $mapping=MathBinder_Canvas_Repository::mapping('user',$external_user,$settings);
        if (!$mapping || ($mapping['status'] ?? '') !== 'approved' || ($mapping['mathbinder_type'] ?? '') !== 'user' || !get_userdata(absint($mapping['mathbinder_id']))) {
            return new WP_Error('mb_canvas_identity_pending','Your Canvas identity is waiting for administrator approval in MathBinder. No work was submitted.',['status'=>403]);
        }
        $course_mapping=MathBinder_Canvas_Repository::mapping('context',(string)($context['id']??''),$settings);
        if(!$course_mapping||($course_mapping['status']??'')!=='approved'||($course_mapping['mathbinder_type']??'')!=='class'||!absint($course_mapping['mathbinder_id']))return new WP_Error('mb_canvas_course_pending','This Canvas course is waiting for administrator mapping to a MathBinder class. No work was submitted.',['status'=>403]);
        global $wpdb;$enrolled=(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$wpdb->prefix}mb_enrollments WHERE class_id=%d AND user_id=%d AND role_key='student' AND status='active'",absint($course_mapping['mathbinder_id']),absint($mapping['mathbinder_id'])));if(!$enrolled)return new WP_Error('mb_canvas_enrollment','The approved Canvas identity is not actively enrolled in the mapped MathBinder class.',['status'=>403]);
        $deep=(array)($claims['https://purl.imsglobal.org/spec/lti-dl/claim/deep_linking_settings'] ?? []);
        $return_url=esc_url_raw((string)($deep['deep_link_return_url'] ?? ''));
        if ($return_url==='' || !self::trusted_canvas_url($return_url,$settings)) return new WP_Error('mb_canvas_return_url','Canvas did not provide an approved Deep Linking return URL.',['status'=>400]);
        $token=MathBinder_Canvas_Crypto::b64url_encode(random_bytes(32));
        set_transient(self::LAUNCH_PREFIX.hash('sha256',$token),[
            'student_id'=>absint($mapping['mathbinder_id']),'external_user_id'=>$external_user,'return_url'=>$return_url,
            'data'=>(string)($deep['data'] ?? ''),'aud'=>rtrim((string)($claims['iss']??$settings['platform_issuer']??$settings['canvas_url']),'/'),
            'context_id'=>(string)($context['id'] ?? ''),'class_id'=>absint($course_mapping['mathbinder_id']),'created_at'=>time(),
        ],20*MINUTE_IN_SECONDS);
        return new WP_REST_Response(null,303,['Location'=>add_query_arg('mathbinder_canvas_submission',$token,home_url('/'))]);
    }

    public static function route_pages() {
        if (isset($_GET['mathbinder_canvas_submission'])) self::render_selector(sanitize_text_field(wp_unslash($_GET['mathbinder_canvas_submission'])));
        if (isset($_GET['mb_canvas_evidence'])) self::render_evidence(sanitize_text_field(wp_unslash($_GET['mb_canvas_evidence'])));
    }

    private static function launch($token) { $value=get_transient(self::LAUNCH_PREFIX.hash('sha256',(string)$token)); return is_array($value)?$value:[]; }
    private static function selectable_notes($student_id,$class_id) {
        return array_values(array_filter(MathBinder_Math_Notes::all($student_id),function($note)use($class_id){ return absint($note['class_id']??0)===absint($class_id)&&!empty($note['submitted_snapshot'])&&in_array($note['status']??'', ['submitted','feedback','revision_requested','graded'],true); }));
    }
    private static function render_selector($token) {
        $launch=self::launch($token); if(!$launch) self::page('Canvas submission expired','Return to the Canvas assignment and open MathBinder again.');
        $student=get_userdata(absint($launch['student_id'])); $notes=self::selectable_notes($launch['student_id'],$launch['class_id']);
        status_header(200); nocache_headers(); header('Content-Type: text/html; charset='.get_option('blog_charset')); ?><!doctype html><html><head><meta charset="<?php bloginfo('charset'); ?>"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Select MathBinder Notes</title><style><?php echo self::page_css(); ?></style></head><body><main><header><span>MATHBINDER + CANVAS</span><h1>Select notes to submit</h1><p><?php echo esc_html($student?$student->display_name:'Student'); ?>, choose one or more locked MathBinder snapshots for this Canvas assignment.</p></header><div class="privacy"><strong>You are in control.</strong> Private drafts are not shown. Canvas receives only the exact snapshots you select.</div><?php if(!$notes): ?><section><h2>No submitted snapshots are ready</h2><p>Return to MathBinder, submit a note version to your teacher, and then reopen this Canvas assignment.</p></section><?php else: ?><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="mathbinder_canvas_submit_notes"><input type="hidden" name="launch_token" value="<?php echo esc_attr($token); ?>"><div class="notes"><?php foreach(array_reverse($notes) as $note): $s=$note['submitted_snapshot']; ?><label class="note"><input type="checkbox" name="note_ids[]" value="<?php echo esc_attr($note['id']); ?>"><span><small><?php echo esc_html(ucfirst($s['organization_type']??'topic').' · Snapshot v'.absint($s['version']??1)); ?></small><strong><?php echo esc_html($s['title']??'Math Note'); ?></strong><em><?php echo esc_html($s['organization_label']??''); ?><?php echo !empty($s['subcategory_label'])?' → '.$s['subcategory_label']:''; ?></em></span></label><?php endforeach; ?></div><button type="submit">Submit selected snapshots to Canvas</button></form><?php endif; ?><footer>MathBinder preserves the original work and submission version.</footer></main></body></html><?php exit;
    }
    private static function page($title,$message) { status_header(400); nocache_headers(); ?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title><?php echo esc_html($title); ?></title><style><?php echo self::page_css(); ?></style></head><body><main><section><h1><?php echo esc_html($title); ?></h1><p><?php echo esc_html($message); ?></p></section></main></body></html><?php exit; }
    private static function page_css(){return 'body{margin:0;background:#f3f8fa;color:#17233b;font:17px system-ui,sans-serif}main{max-width:900px;margin:0 auto;padding:30px}header,section,.privacy,form{background:#fff;border:1px solid #d7e2e7;border-radius:18px;padding:24px;margin-bottom:18px}header{border-left:8px solid #078b8f}header span{color:#08777b;font-weight:900;letter-spacing:.12em}h1{color:#4c2691}.privacy{background:#eafaf4;border-left:6px solid #078b8f}.notes{display:grid;gap:12px}.note{display:flex;gap:14px;padding:16px;border:1px solid #d8cff3;border-radius:12px;cursor:pointer}.note input{width:22px}.note span{display:grid;gap:5px}.note strong{font-size:1.15rem}.note small,.note em{color:#59677a}button{margin-top:20px;padding:14px 20px;border:0;border-radius:12px;background:#6d28d9;color:#fff;font-weight:900;font-size:1rem}footer{text-align:center;color:#687487;padding:16px}img{max-width:100%;height:auto;border:1px solid #d8e0e6;border-radius:10px}.snapshot{background:#fff;border:1px solid #d8e0e6;border-radius:16px;padding:22px;margin:18px 0;white-space:pre-wrap}';}

    public static function submit_notes() {
        $token=sanitize_text_field(wp_unslash($_POST['launch_token']??'')); $launch=self::launch($token); if(!$launch) self::page('Canvas submission expired','Return to Canvas and open the assignment again.');
        $ids=array_values(array_unique(array_filter(array_map('sanitize_key',(array)($_POST['note_ids']??[]))))); if(!$ids) self::page('Choose at least one note','Use your browser Back button and select the snapshots you want to submit.');
        $available=[]; foreach(self::selectable_notes($launch['student_id'],$launch['class_id']) as $note)$available[$note['id']]=$note;
        $selected=[]; foreach(array_slice($ids,0,20) as $id)if(isset($available[$id]))$selected[]=['id'=>$id,'version'=>absint($available[$id]['submitted_snapshot']['version']??1)];
        if(!$selected)self::page('No valid snapshots selected','Return to Canvas and try again.');
        $evidence=self::evidence_token(absint($launch['student_id']),$selected); $evidence_url=add_query_arg('mb_canvas_evidence',$evidence,home_url('/'));
        $titles=[]; foreach($selected as $item)$titles[]=$available[$item['id']]['submitted_snapshot']['title']??'Math Note';
        $item=['type'=>'ltiResourceLink','title'=>'MathBinder Notes: '.implode(', ',array_slice($titles,0,3)),'url'=>$evidence_url,'presentation'=>['documentTarget'=>'iframe'],'custom'=>['mathbinder_snapshot_count'=>(string)count($selected)]];
        $jwt=MathBinder_Canvas_Integration::adapter()->create_deep_link(['aud'=>$launch['aud'],'data'=>$launch['data'],'content_items'=>[$item]]); if(is_wp_error($jwt))self::page('Canvas submission could not be signed',$jwt->get_error_message());
        delete_transient(self::LAUNCH_PREFIX.hash('sha256',$token)); MathBinder_Audit_Log::record('submit','canvas_note_selection',$launch['student_id'],['snapshot_count'=>count($selected),'context_hash'=>hash('sha256',$launch['context_id'])]);
        status_header(200); nocache_headers(); ?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Returning to Canvas</title><style><?php echo self::page_css(); ?></style></head><body><main><section><h1>Submitting to Canvas…</h1><p>Your selected locked snapshots are being returned to the Canvas assignment.</p><form id="mb-return" method="post" action="<?php echo esc_url($launch['return_url']); ?>"><input type="hidden" name="JWT" value="<?php echo esc_attr($jwt); ?>"><button type="submit">Return to Canvas</button></form></section></main><script>document.getElementById('mb-return').submit();</script></body></html><?php exit;
    }

    private static function evidence_token($student_id,array $selected){$payload=MathBinder_Canvas_Crypto::b64url_encode(wp_json_encode(['student_id'=>$student_id,'notes'=>$selected,'exp'=>time()+180*DAY_IN_SECONDS]));$sig=MathBinder_Canvas_Crypto::b64url_encode(hash_hmac('sha256',$payload,wp_salt('auth'),true));return $payload.'.'.$sig;}
    private static function evidence_claims($token){$parts=explode('.',$token);if(count($parts)!==2)return[];$sig=MathBinder_Canvas_Crypto::b64url_encode(hash_hmac('sha256',$parts[0],wp_salt('auth'),true));if(!hash_equals($sig,$parts[1]))return[];$json=MathBinder_Canvas_Crypto::b64url_decode($parts[0]);$data=json_decode($json,true);return is_array($data)&&($data['exp']??0)>=time()?$data:[];}
    private static function render_evidence($token){$claims=self::evidence_claims($token);if(!$claims)self::page('Evidence link unavailable','This secure MathBinder evidence link is invalid or expired.');$all=MathBinder_Math_Notes::all(absint($claims['student_id']));$snapshots=[];foreach((array)$claims['notes'] as $item){$note=$all[sanitize_key($item['id']??'')]??null;$version=(string)absint($item['version']??0);$snapshot=$note['submission_history'][$version]??($note['submitted_snapshot']??null);if($snapshot&&absint($snapshot['version']??0)===absint($version))$snapshots[]=$snapshot;}if(!$snapshots)self::page('Evidence unavailable','The submitted snapshots could not be verified.');status_header(200);nocache_headers();header('Content-Type: text/html; charset='.get_option('blog_charset'));?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>MathBinder Submission Evidence</title><style><?php echo self::page_css(); ?></style></head><body><main><header><span>LOCKED MATHBINDER EVIDENCE</span><h1>Student note submission</h1><p>This page shows the exact version selected for Canvas.</p></header><?php foreach($snapshots as $s):?><article class="snapshot"><small>Snapshot v<?php echo absint($s['version']);?> · <?php echo esc_html($s['submitted_at']);?></small><h2><?php echo esc_html($s['title']);?></h2><p><strong><?php echo esc_html(ucfirst($s['organization_type']??'topic'));?>:</strong> <?php echo esc_html($s['organization_label']??'');?><?php echo !empty($s['subcategory_label'])?' → '.esc_html($s['subcategory_label']):'';?></p><?php echo wp_kses_post(wpautop($s['content']??''));?><?php if(!empty($s['drawing_data'])):?><img src="<?php echo esc_attr($s['drawing_data']);?>" alt="Submitted math drawing"><?php endif;?></article><?php endforeach;?></main></body></html><?php exit;}

    public static function grade_button(array $note,$student_id){if(($note['status']??'')!=='graded')return'';$mapping=MathBinder_Canvas_Repository::approved_for_mathbinder('user',absint($student_id),MathBinder_Canvas_Settings::get());$meta=$mapping?json_decode($mapping['metadata_json']??'{}',true):[];$readiness=MathBinder_Canvas_Protocol::readiness();$ready=$mapping&&!empty($meta['scores_url'])&&!empty($readiness['live_transport_enabled']);ob_start();?><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>" onsubmit="return confirm('Send this teacher-approved grade and feedback to Canvas SpeedGrader?');"><input type="hidden" name="action" value="mb_teacher_canvas_send_grade"><input type="hidden" name="student_id" value="<?php echo absint($student_id);?>"><input type="hidden" name="note_id" value="<?php echo esc_attr($note['id']);?>"><?php wp_nonce_field('mb_teacher_canvas_send_grade','mb_canvas_grade_nonce');?><button type="submit" <?php disabled(!$ready);?>><?php echo $ready?'Send Grade to Canvas SpeedGrader':'Canvas assignment mapping and sandbox gate required';?></button></form><?php return ob_get_clean();}
    public static function send_grade(){if(!is_user_logged_in())wp_die('Teacher access required.','',['response'=>403]);check_admin_referer('mb_teacher_canvas_send_grade','mb_canvas_grade_nonce');$teacher=get_current_user_id();$student=absint($_POST['student_id']??0);$id=sanitize_key(wp_unslash($_POST['note_id']??''));$notes=MathBinder_Math_Notes::all($student);$note=$notes[$id]??null;if(!$note||($note['status']??'')!=='graded'||!MathBinder_Math_Notes::can_teacher_review($teacher,$student,absint($note['class_id']??0)))wp_die('This grade is not available for Canvas passback.','',['response'=>403]);$settings=MathBinder_Canvas_Settings::get();$readiness=MathBinder_Canvas_Protocol::readiness();if(empty($readiness['live_transport_enabled']))wp_die('The authorized Canvas sandbox transmission gate is not enabled.','',['response'=>403]);$mapping=MathBinder_Canvas_Repository::approved_for_mathbinder('user',$student,$settings);if(!$mapping)wp_die('An approved Canvas user mapping is required.','',['response'=>400]);$meta=json_decode($mapping['metadata_json']??'{}',true);$review=(array)$note['review'];$type=$review['grade_type']??'points';$score=(float)($review['score']??0);$maximum=(float)($review['points_possible']??0);if($type==='percentage')$maximum=100;if($type==='completion'){$maximum=1;$score=$score>0?1:0;}if($maximum<=0)wp_die('A positive points-possible value is required for Canvas grade passback.','',['response'=>400]);$payload=['teacher_approved'=>true,'scores_url'=>$meta['scores_url']??'','user_id'=>$mapping['external_id'],'score'=>$score,'maximum'=>$maximum,'comment'=>wp_strip_all_tags($review['feedback']??''),'note_id'=>$id,'snapshot_version'=>absint($note['submitted_snapshot']['version']??0)];$job=MathBinder_Canvas_Repository::queue('grade_passback','math_note',$id,array_diff_key($payload,['user_id'=>1]),$settings,$mapping['external_id']);$result=MathBinder_Canvas_Integration::adapter()->pass_grade($payload);MathBinder_Canvas_Repository::finish_job($job,$result);MathBinder_Audit_Log::record(is_wp_error($result)?'failed':'sent','canvas_grade',$id,['student_id'=>$student,'job_id'=>$job,'snapshot_version'=>$payload['snapshot_version']]);$url=add_query_arg(['student'=>$student,'notes_notice'=>is_wp_error($result)?'canvas_grade_failed':'canvas_grade_sent'],home_url('/teacher-dashboard/')).'#submitted-math-notes';wp_safe_redirect($url);exit;}

    public static function approve_mapping(){if(!current_user_can(MathBinder_Capabilities::MANAGE_INTEGRATIONS))wp_die('Canvas administrator access required.','',['response'=>403]);check_admin_referer('mathbinder_canvas_approve_mapping','mathbinder_canvas_mapping_nonce');$id=absint($_POST['mapping_id']??0);$target=absint($_POST['mathbinder_id']??0);$mapping=MathBinder_Canvas_Repository::mapping_by_id($id,MathBinder_Canvas_Settings::get());if(!$mapping||!$target)wp_die('Mapping information is invalid.','',['response'=>400]);$type=$mapping['mapping_type']==='context'?'class':'user';if($type==='user'&&!get_userdata($target))wp_die('MathBinder user not found.','',['response'=>400]);if($type==='class'){global $wpdb;if(!(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$wpdb->prefix}mb_classes WHERE id=%d",$target)))wp_die('MathBinder class not found.','',['response'=>400]);}MathBinder_Canvas_Repository::approve_mapping($id,$type,$target,MathBinder_Canvas_Settings::get());MathBinder_Audit_Log::record('approve','canvas_mapping',$id,['mathbinder_type'=>$type,'mathbinder_id'=>$target]);wp_safe_redirect(add_query_arg('canvas_mapping','approved',admin_url('options-general.php?page='.MathBinder_Canvas_Settings::PAGE_SLUG.'#testing')));exit;}
    private static function is_learner(array $roles){foreach($roles as $role)if(stripos((string)$role,'learner')!==false||stripos((string)$role,'student')!==false)return true;return false;}
    private static function trusted_canvas_url($url,array $settings){$candidate=wp_parse_url($url);$canvas=wp_parse_url($settings['canvas_url']??'');return is_array($candidate)&&is_array($canvas)&&strtolower((string)($candidate['scheme']??''))==='https'&&strtolower((string)($candidate['host']??''))===strtolower((string)($canvas['host']??''))&&absint($candidate['port']??443)===absint($canvas['port']??443);}
}
