<?php
if (!defined('ABSPATH')) exit;
final class MathBinder_Organization_Admin {
    public static function register(){ add_action('admin_menu',[__CLASS__,'menu']); foreach(['organization','term','class','enrollment','license','seat'] as $a)add_action('admin_post_mb_create_'.$a,[__CLASS__,'handle']); add_action('admin_post_mb_update_record_status',[__CLASS__,'handle']); }
    public static function menu(){ add_menu_page('MathBinder Organizations','MathBinder Organizations',MathBinder_Capabilities::MANAGE_ORGANIZATIONS,'mathbinder-organizations',[__CLASS__,'render'],'dashicons-building',21); }
    private static function redirect($ok=true){wp_safe_redirect(add_query_arg($ok?'mb_org_updated':'mb_org_error','1',wp_get_referer()));exit;}
    public static function handle(){ if(!current_user_can(MathBinder_Capabilities::MANAGE_ORGANIZATIONS))wp_die('Not authorized.',403); $action=sanitize_key($_POST['action']??''); check_admin_referer($action); $s='MathBinder_Organization_Service'; $r=true;
        if($action==='mb_create_organization')$r=$s::create_organization($_POST['name']??'',$_POST['organization_type']??'school');
        elseif($action==='mb_create_term')$r=$s::create_term($_POST['organization_id']??0,$_POST['name']??'',$_POST['starts_on']??'',$_POST['ends_on']??'');
        elseif($action==='mb_create_class')$r=$s::create_class($_POST['organization_id']??0,$_POST['term_id']??0,$_POST['name']??'',$_POST['section_name']??'',$_POST['teacher_user_id']??0);
        elseif($action==='mb_create_enrollment')$r=$s::enroll($_POST['class_id']??0,$_POST['email']??'',$_POST['role_key']??'student');
        elseif($action==='mb_create_license')$r=$s::create_license($_POST['organization_id']??0,$_POST['seat_limit']??0,$_POST['trial_days']??30);
        elseif($action==='mb_create_seat')$r=$s::allocate_seat($_POST['license_id']??0,$_POST['email']??'');
        elseif($action==='mb_update_record_status')$r=$s::update_record_status($_POST['record_type']??'',$_POST['record_id']??0,$_POST['status']??'');
        self::redirect(!is_wp_error($r)); }
    private static function form($action,$title,$fields){ echo '<div class="card" style="max-width:700px"><h2>'.esc_html($title).'</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="'.esc_attr($action).'">'; wp_nonce_field($action); foreach($fields as $n=>$f)echo '<p><label>'.esc_html($f[0]).'<br><input class="regular-text" '.(!empty($f[2])?'required ':'').'type="'.esc_attr($f[1]).'" name="'.esc_attr($n).'"></label></p>'; submit_button($title); echo '</form></div>'; }
    private static function status_form($type,$id,$current,$choices){ echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'" style="display:flex;gap:6px;align-items:center"><input type="hidden" name="action" value="mb_update_record_status"><input type="hidden" name="record_type" value="'.esc_attr($type).'"><input type="hidden" name="record_id" value="'.(int)$id.'">'; wp_nonce_field('mb_update_record_status'); echo '<select name="status" aria-label="Change status">'; foreach($choices as $choice)echo '<option value="'.esc_attr($choice).'" '.selected($current,$choice,false).'>'.esc_html(ucfirst($choice)).'</option>'; echo '</select><button class="button button-small">Update</button></form>'; }
    public static function render(){ global $wpdb; if(!current_user_can(MathBinder_Capabilities::MANAGE_ORGANIZATIONS))return; $orgs=MathBinder_Organization_Service::organizations(); $terms=$wpdb->get_results("SELECT t.*,o.name organization_name FROM {$wpdb->prefix}mb_terms t JOIN {$wpdb->prefix}mb_organizations o ON o.id=t.organization_id ORDER BY t.id DESC",ARRAY_A)?:[]; $classes=$wpdb->get_results("SELECT c.*,o.name organization_name,t.name term_name,u.display_name teacher_name,u.user_email teacher_email,(SELECT COUNT(*) FROM {$wpdb->prefix}mb_enrollments e WHERE e.class_id=c.id AND e.status='active') active_enrollments FROM {$wpdb->prefix}mb_classes c JOIN {$wpdb->prefix}mb_organizations o ON o.id=c.organization_id LEFT JOIN {$wpdb->prefix}mb_terms t ON t.id=c.term_id LEFT JOIN {$wpdb->prefix}users u ON u.ID=c.teacher_user_id ORDER BY c.id DESC",ARRAY_A)?:[]; $enrollments=$wpdb->get_results("SELECT e.*,c.name class_name,c.section_name,u.display_name,u.user_email FROM {$wpdb->prefix}mb_enrollments e JOIN {$wpdb->prefix}mb_classes c ON c.id=e.class_id LEFT JOIN {$wpdb->prefix}users u ON u.ID=e.user_id ORDER BY e.id DESC",ARRAY_A)?:[]; $licenses=$wpdb->get_results("SELECT l.*,o.name organization_name,(SELECT COUNT(*) FROM {$wpdb->prefix}mb_seat_allocations s WHERE s.license_id=l.id AND s.status='active') seats_used FROM {$wpdb->prefix}mb_licenses l JOIN {$wpdb->prefix}mb_organizations o ON o.id=l.organization_id ORDER BY l.id DESC",ARRAY_A)?:[]; $seats=$wpdb->get_results("SELECT s.*,l.organization_id,o.name organization_name,u.display_name,u.user_email allocator_email FROM {$wpdb->prefix}mb_seat_allocations s JOIN {$wpdb->prefix}mb_licenses l ON l.id=s.license_id JOIN {$wpdb->prefix}mb_organizations o ON o.id=l.organization_id LEFT JOIN {$wpdb->prefix}users u ON u.ID=s.allocated_by ORDER BY s.id DESC",ARRAY_A)?:[]; ?>
      <div class="wrap"><h1>MathBinder Organizations &amp; Licensing</h1><p>Create the organization first, then use its numeric ID for terms, classes, and licenses. All actions are audited.</p>
      <?php if(isset($_GET['mb_org_updated'])):?><div class="notice notice-success is-dismissible"><p>MathBinder record created successfully.</p></div><?php endif;?>
      <?php if(isset($_GET['mb_org_error'])):?><div class="notice notice-error"><p>The MathBinder record could not be created. Check the entered IDs and try again.</p></div><?php endif;?>
      <h2>Organizations</h2><table class="widefat striped"><thead><tr><th>ID</th><th>Name</th><th>Type</th><th>Verification</th><th>Status</th></tr></thead><tbody><?php foreach($orgs as $o):?><tr><td><?php echo(int)$o['id'];?></td><td><?php echo esc_html($o['name']);?></td><td><?php echo esc_html($o['organization_type']);?></td><td><?php echo esc_html($o['verification_status']);?></td><td><?php self::status_form('organization',$o['id'],$o['status'],['active','inactive','archived']);?></td></tr><?php endforeach;?></tbody></table>
      <?php self::form('mb_create_organization','Create organization',['name'=>['Name','text',1],'organization_type'=>['Type (school, district, family)','text',1]]); self::form('mb_create_term','Create term',['organization_id'=>['Organization ID','number',1],'name'=>['Term name','text',1],'starts_on'=>['Start date','date',0],'ends_on'=>['End date','date',0]]); ?>
      <h2>Terms</h2><table class="widefat striped"><thead><tr><th>ID</th><th>Organization</th><th>Term</th><th>Start</th><th>End</th><th>Status</th></tr></thead><tbody><?php if(!$terms):?><tr><td colspan="6">No terms created yet.</td></tr><?php else: foreach($terms as $t):?><tr><td><?php echo(int)$t['id'];?></td><td><?php echo esc_html($t['organization_name']);?></td><td><?php echo esc_html($t['name']);?></td><td><?php echo esc_html($t['starts_on']);?></td><td><?php echo esc_html($t['ends_on']);?></td><td><?php self::status_form('term',$t['id'],$t['status'],['active','inactive','archived']);?></td></tr><?php endforeach; endif;?></tbody></table>
      <?php self::form('mb_create_class','Create class',['organization_id'=>['Organization ID','number',1],'term_id'=>['Term ID','number',0],'name'=>['Class name','text',1],'section_name'=>['Section','text',0],'teacher_user_id'=>['Teacher user ID','number',0]]); ?>
      <h2>Classes</h2><table class="widefat striped"><thead><tr><th>ID</th><th>Organization / Term</th><th>Class</th><th>Teacher</th><th>Students</th><th>Code</th><th>Status</th></tr></thead><tbody><?php if(!$classes):?><tr><td colspan="7">No classes created yet.</td></tr><?php else: foreach($classes as $c):?><tr><td><?php echo(int)$c['id'];?></td><td><?php echo esc_html($c['organization_name']);?><br><small><?php echo esc_html($c['term_name']?:'No term'); ?></small></td><td><?php echo esc_html(trim($c['name'].' '.$c['section_name']));?></td><td><?php echo esc_html($c['teacher_name']?:($c['teacher_email']?:'Unassigned'));?></td><td><?php echo(int)$c['active_enrollments'];?></td><td><code><?php echo esc_html($c['class_code']);?></code></td><td><?php self::status_form('class',$c['id'],$c['status'],['active','inactive','archived']);?></td></tr><?php endforeach; endif;?></tbody></table>
      <?php self::form('mb_create_enrollment','Enroll or invite',['class_id'=>['Class ID','number',1],'email'=>['Account email','email',1],'role_key'=>['Role (student or teacher)','text',1]]); ?>
      <h2>Enrollments &amp; invitations</h2><table class="widefat striped"><thead><tr><th>ID</th><th>Class</th><th>Account</th><th>Role</th><th>Status</th></tr></thead><tbody><?php if(!$enrollments):?><tr><td colspan="5">No enrollments or invitations yet.</td></tr><?php else: foreach($enrollments as $e):?><tr><td><?php echo(int)$e['id'];?></td><td><?php echo esc_html(trim($e['class_name'].' '.$e['section_name']));?></td><td><?php echo esc_html($e['display_name']?:($e['user_email']?:$e['invited_email']));?></td><td><?php echo esc_html($e['role_key']);?></td><td><?php self::status_form('enrollment',$e['id'],$e['status'],['active','invited','inactive','removed']);?></td></tr><?php endforeach; endif;?></tbody></table>
      <?php self::form('mb_create_license','Start trial license',['organization_id'=>['Organization ID','number',1],'seat_limit'=>['Seat limit','number',1],'trial_days'=>['Trial days','number',1]]); ?>
      <h2>License coverage</h2><table class="widefat striped"><thead><tr><th>ID</th><th>Organization</th><th>Seats</th><th>Trial ends</th><th>Status</th></tr></thead><tbody><?php if(!$licenses):?><tr><td colspan="5">No licenses created yet.</td></tr><?php else: foreach($licenses as $l):?><tr><td><?php echo(int)$l['id'];?></td><td><?php echo esc_html($l['organization_name']);?></td><td><?php echo(int)$l['seats_used'].' / '.(int)$l['seat_limit'];?></td><td><?php echo esc_html($l['trial_ends_at']);?></td><td><?php self::status_form('license',$l['id'],$l['status'],['trial','active','grace','inactive','canceled']);?></td></tr><?php endforeach; endif;?></tbody></table>
      <?php self::form('mb_create_seat','Allocate premium seat',['license_id'=>['License ID','number',1],'email'=>['Admin account email','email',1]]); ?>
      <h2>Premium seat allocations</h2><p>Seat emails identify the covered administrator account. A matching WordPress user is optional at allocation time and will be linked automatically when available.</p><table class="widefat striped"><thead><tr><th>ID</th><th>Organization</th><th>License</th><th>Account email</th><th>Linked user</th><th>Allocated</th><th>Status</th></tr></thead><tbody><?php if(!$seats):?><tr><td colspan="7">No premium seats allocated yet.</td></tr><?php else: foreach($seats as $seat):?><tr><td><?php echo(int)$seat['id'];?></td><td><?php echo esc_html($seat['organization_name']);?></td><td><?php echo(int)$seat['license_id'];?></td><td><?php echo esc_html($seat['account_email']);?></td><td><?php echo $seat['user_id']?('User #'.(int)$seat['user_id']):'Pending account link';?></td><td><?php echo esc_html($seat['created_at']);?></td><td><?php self::status_form('seat',$seat['id'],$seat['status'],['active','revoked']);?></td></tr><?php endforeach; endif;?></tbody></table></div><?php }
}
