<?php
if (!defined('ABSPATH')) exit;

/* Complete Grades 3–5 Number & Operations—Fractions lesson set. */
$lessons = [
    '3-fractions-as-numbers' => ['title'=>'Fractions as Numbers','grade'=>'Grade 3','standard'=>'3.NF.A.1, 3.NF.A.2','focus'=>'understand a fraction as equal parts of one whole and as a point on a number line','vocab'=>'fraction — a number that names equal parts; numerator — the number of parts counted; denominator — the number of equal parts in one whole; unit fraction — a fraction with numerator 1; number line — a line that shows numbers in order','example'=>'Show 3/4 on a number line | Divide the distance from 0 to 1 into 4 equal parts because the denominator is 4. | Start at 0 and count 3 equal jumps because the numerator is 3. | The third mark is 3/4.','warm'=>'A rectangle is split into 6 equal parts. Two parts are shaded. What fraction is shaded? | 2/6','guided'=>'Mark 3/5 on a number line from 0 to 1. How many equal jumps reach 3/5? | 3','independent'=>'A whole is divided into 8 equal parts. Write the unit fraction for one part. | 1/8','challenge'=>'Draw two different shapes that each show 3/4. Explain why both models represent the same fraction.'],
    '3-equivalent-fractions' => ['title'=>'Equivalent Fractions','grade'=>'Grade 3','standard'=>'3.NF.A.3','focus'=>'recognize and create fractions that name the same amount','vocab'=>'equivalent fractions — fractions with the same value; numerator — parts counted; denominator — equal parts in a whole; model — a picture that shows a mathematical idea; equal — the same value','example'=>'Show why 1/2 = 2/4 | Shade 1 of 2 equal parts in the first bar. | Split each half into 2 equal pieces, making 4 equal parts. | The same shaded amount now covers 2 of 4 parts, so 1/2 = 2/4.','warm'=>'Which fraction is equivalent to 1/2: 2/4 or 2/3? | 2/4','guided'=>'Complete the equation 2/3 = ?/6. | 4/6','independent'=>'Write a fraction equivalent to 3/4 with denominator 8. | 6/8','challenge'=>'Find three fractions equivalent to 2/5 and explain the pattern in the numerators and denominators.'],
    '3-compare-fractions' => ['title'=>'Compare Fractions','grade'=>'Grade 3','standard'=>'3.NF.A.3.D','focus'=>'compare fractions that refer to the same whole','vocab'=>'compare — decide which value is greater, less, or equal; greater than — a larger value; less than — a smaller value; benchmark fraction — a familiar fraction such as 0, 1/2, or 1; same whole — models with equal total size','example'=>'Compare 3/8 and 5/8 | The denominators are the same, so the pieces are the same size. | Compare the numerators: 5 parts is more than 3 parts. | Therefore 3/8 < 5/8.','warm'=>'Compare 2/6 and 5/6 using <, >, or =. | 2/6 < 5/6','guided'=>'Which is greater, 3/4 or 3/8? | 3/4','independent'=>'Compare 2/3 and 3/4 using a model. | 2/3 < 3/4','challenge'=>'Find a fraction greater than 1/2 but less than 3/4. Prove it with a model or number line.'],
    '4-equivalent-fractions-simplest-form' => ['title'=>'Equivalent Fractions and Simplest Form','grade'=>'Grade 4','standard'=>'4.NF.A.1','focus'=>'generate equivalent fractions and rename fractions in simplest form','vocab'=>'equivalent — equal in value; factor — a number multiplied to make a product; common factor — a factor shared by two numbers; simplest form — numerator and denominator share no factor greater than 1; rename — write an equal value in another form','example'=>'Simplify 6/8 | The numerator and denominator share a factor of 2. | Divide both by 2: 6 ÷ 2 = 3 and 8 ÷ 2 = 4. | Therefore 6/8 = 3/4, and 3/4 is in simplest form.','warm'=>'Complete 3/5 = ?/10. | 6/10','guided'=>'Write 8/12 in simplest form. | 2/3','independent'=>'Find two fractions equivalent to 5/6. | 10/12 and 15/18','challenge'=>'Explain why multiplying the numerator and denominator by the same nonzero number keeps a fraction equivalent.'],
    '4-add-subtract-fractions' => ['title'=>'Add and Subtract Fractions','grade'=>'Grade 4','standard'=>'4.NF.B.3','focus'=>'add and subtract fractions and mixed numbers with like denominators','vocab'=>'like denominators — fractions with the same denominator; mixed number — a whole number and a fraction; sum — an addition result; difference — a subtraction result; decompose — break into useful parts','example'=>'Add 2/8 + 5/8 | The pieces are eighths, so keep denominator 8. | Combine the counted pieces: 2 eighths + 5 eighths = 7 eighths. | The sum is 7/8.','warm'=>'Find 3/10 + 4/10. | 7/10','guided'=>'Solve 1 2/6 + 3/6. | 1 5/6','independent'=>'Find 2 7/8 − 5/8. | 2 1/4','challenge'=>'Create a fraction story problem whose answer is 1 1/2 and solve it two ways.'],
    '4-multiply-fractions-whole-numbers' => ['title'=>'Multiply Fractions by Whole Numbers','grade'=>'Grade 4','standard'=>'4.NF.B.4','focus'=>'multiply a fraction by a whole number as repeated addition','vocab'=>'multiple — a product of a number and a whole number; repeated addition — adding equal groups; product — a multiplication result; unit fraction — one equal part; fraction model — a drawing of equal fractional parts','example'=>'Find 3 × 2/5 | Think of 3 groups of 2/5: 2/5 + 2/5 + 2/5. | Add the numerators and keep fifth-size pieces: 6/5. | Rename 6/5 as 1 1/5.','warm'=>'Find 4 × 1/6. | 4/6','guided'=>'Solve 3 × 3/8. | 9/8','independent'=>'A ribbon piece is 2/3 meter long. What is the length of 5 pieces? | 10/3 meters','challenge'=>'Write two different whole-number-times-fraction expressions with a product of 3.'],
    '4-decimal-notation-comparison' => ['title'=>'Decimal Notation and Comparison','grade'=>'Grade 4','standard'=>'4.NF.C.5, 4.NF.C.6, 4.NF.C.7','focus'=>'connect fractions with denominators 10 and 100 to decimal notation and compare decimals','vocab'=>'decimal — another way to write a fraction with a power-of-ten denominator; tenths — equal parts when a whole is divided into 10; hundredths — equal parts when divided into 100; decimal point — separates whole-number and fractional places; equivalent — equal in value','example'=>'Write 37/100 as a decimal | The denominator 100 means hundredths. | Put 37 in the hundredths places: 3 tenths and 7 hundredths. | Therefore 37/100 = 0.37.','warm'=>'Write 6/10 as a decimal. | 0.6','guided'=>'Compare 0.45 and 0.54 using <, >, or =. | 0.45 < 0.54','independent'=>'Write 8/10 + 3/100 as one decimal. | 0.83','challenge'=>'Find three decimals between 0.4 and 0.5 and write each as a fraction with denominator 100.'],
    '5-add-subtract-fractions-unlike-denominators' => ['title'=>'Add and Subtract Fractions with Unlike Denominators','grade'=>'Grade 5','standard'=>'5.NF.A.1, 5.NF.A.2','focus'=>'add and subtract fractions with unlike denominators using equivalent fractions','vocab'=>'unlike denominators — different-sized fractional units; common denominator — a shared denominator; equivalent fractions — fractions with the same value; sum — addition result; difference — subtraction result','example'=>'Add 2/3 + 1/4 | Use a common denominator of 12. | Rename 2/3 as 8/12 and 1/4 as 3/12. | Add: 8/12 + 3/12 = 11/12.','warm'=>'Find 1/2 + 1/3. | 5/6','guided'=>'Solve 3/4 − 1/6. | 7/12','independent'=>'Maya walked 2/5 mile and then 3/8 mile. How far did she walk? | 31/40 mile','challenge'=>'Create two unlike fractions whose sum is exactly 1 and explain how you know.'],
    '5-multiply-fractions' => ['title'=>'Multiply Fractions','grade'=>'Grade 5','standard'=>'5.NF.B.3, 5.NF.B.4, 5.NF.B.5, 5.NF.B.6','focus'=>'interpret and calculate products involving fractions','vocab'=>'product — multiplication result; of — often signals multiplication in a fraction context; scaling — changing size by a factor; area model — overlapping lengths and widths; improper fraction — numerator at least as large as denominator','example'=>'Find 2/3 × 3/4 | Draw a rectangle and shade 2/3 in one direction. | Shade 3/4 in the other direction. The overlap is 6 of 12 equal parts. | Simplify 6/12 to 1/2.','warm'=>'Find 1/2 × 3/5. | 3/10','guided'=>'Solve 4/7 × 2/3. | 8/21','independent'=>'A garden is 3/4 yard long and 2/5 yard wide. What is its area? | 3/10 square yard','challenge'=>'Give an example showing that multiplying by a fraction less than 1 makes a positive number smaller. Explain why.'],
    '5-divide-unit-fractions-whole-numbers' => ['title'=>'Divide Unit Fractions and Whole Numbers','grade'=>'Grade 5','standard'=>'5.NF.B.7','focus'=>'divide unit fractions by whole numbers and whole numbers by unit fractions','vocab'=>'unit fraction — a fraction with numerator 1; quotient — division result; partition — split equally; measurement division — count how many groups fit; reciprocal relationship — related multiplication and division facts','example'=>'Find 3 ÷ 1/4 | Ask how many one-fourth pieces fit into 3 wholes. | Each whole has 4 fourths, so 3 wholes have 12 fourths. | Therefore 3 ÷ 1/4 = 12.','warm'=>'Find 2 ÷ 1/3. | 6','guided'=>'Solve 1/2 ÷ 4. | 1/8','independent'=>'Four friends share 1/3 of a pan of brownies equally. What fraction of the whole pan does each receive? | 1/12','challenge'=>'Compare 4 ÷ 1/2 and 1/2 ÷ 4. Explain why the quotients are very different.'],
];

$video_urls = [
    'Fractions as Numbers' => 'https://www.youtube.com/watch?v=KGSwhRXMa3M',
    'Equivalent Fractions' => 'https://www.youtube.com/watch?v=G4VxHxwi6DY',
    'Compare Fractions' => 'https://www.youtube.com/watch?v=ONsI-yIbsBg',
    'Equivalent Fractions and Simplest Form' => 'https://www.youtube.com/watch?v=N1X0vf5PUz4',
    'Add and Subtract Fractions' => 'https://www.youtube.com/watch?v=UbUdyE1_b9g',
    'Multiply Fractions by Whole Numbers' => 'https://www.youtube.com/watch?v=6PMQdHCtUtA',
    'Decimal Notation and Comparison' => 'https://www.youtube.com/watch?v=zEd67cLFnuQ',
    'Add and Subtract Fractions with Unlike Denominators' => 'https://www.youtube.com/watch?v=bcCLKACsYJ0',
    'Multiply Fractions' => 'https://www.youtube.com/watch?v=CTKMK1ZGLuk',
    'Divide Unit Fractions and Whole Numbers' => 'https://www.youtube.com/watch?v=RygpFkLCSaM',
];

$expand = function($item) use ($video_urls) {
    $practice = function($raw, $directions) {
        list($question, $answer) = array_map('trim', explode('|', $raw, 2));
        return $directions . ' || ' . $question . ' | ' . $answer
            . ' | Name the whole, identify the size of each equal part, and choose a fraction model before calculating.'
            . ' | Label the numerator and denominator or common unit you need. Stop before finding the final value.'
            . ' | Use the model, write each equivalent-fraction or operation step, simplify when needed, and check against the whole.';
    };
    return [
        'title'=>$item['title'],
        'subtitle'=>'Use equal-part models and number lines to '.$item['focus'].'.',
        'essential_question'=>'How can equal parts and visual models help us '.$item['focus'].'?',
        'learning_targets'=>"I can identify the whole and its equal parts.\nI can choose a fraction model or number line that matches the problem.\nI can calculate, explain, and check my answer.",
        'vocabulary'=>str_replace('; ', "\n", $item['vocab']),
        'worked_examples'=>$item['example'],
        'common_mistakes'=>"Treating the denominator as a count instead of the size of the parts | Name the whole and divide it into equal parts first.\nUsing models with different-sized wholes | Compare fractions only when the wholes are the same size.\nAdding denominators when adding like units | Keep the common unit and combine only the number of those units.\nSkipping a reasonableness check | Compare the result with 0, 1/2, 1, or the original amount.",
        'real_life'=>'Fractions help us measure ingredients, share fairly, describe time and distance, compare data, resize designs, and calculate parts of quantities.',
        'videos'=>$item['title'].' | '.$video_urls[$item['title']],
        'video_chapters'=>"0:00 | Identify the whole and equal parts\n1:00 | Build the visual model\n2:15 | Write the fraction equation\n3:30 | Solve, simplify, and check",
        'practice_warmup'=>$practice($item['warm'],'Use a quick fraction model. Label the whole, equal parts, numerator, and denominator.'),
        'guided_practice'=>$practice($item['guided'],'Follow the steps. Draw a fraction bar or number line, label each value, write an equation, and solve.'),
        'independent_practice'=>$practice($item['independent'],'Choose a fraction model, show each step, simplify when needed, and enter your final answer.'),
        'challenge_practice'=>$item['challenge'],
        'master_it'=>"I can explain what the numerator and denominator mean in this problem.\nI can use an accurate model and equation.\nI can check my result with a benchmark or related operation.",
        'mastery_questions'=>"What must be true about the parts in a fraction model? | They are equal in size ; They have different colors ; There are always ten ; They are all shaded | A\nWhat does the denominator tell? | How many parts are counted ; The size or number of equal parts in one whole ; The final answer ; Which operation to use | B\nWhy use a common denominator when adding unlike fractions? | To rename them with the same-sized units ; To make them decimals ; To change their values ; To avoid a model | A\nWhich is a useful reasonableness check? | Compare with benchmarks such as 0, 1/2, and 1 ; Add every denominator ; Ignore the whole ; Change the numerator | A\nWhy should the visual match the question? | It shows the same whole, parts, and relationship ; It makes every answer 1 ; It removes the need to explain ; It changes the values | A",
        'parent_summary'=>'Students learn fractions as numbers through equal-part models, number lines, equations, and real situations. They explain the meaning of each value before applying a procedure.',
        'parent_conversation'=>"Ask: What is the whole?\nAsk: How many equal parts make the whole, and how many are being counted?\nAsk: Which benchmark or model shows that the answer makes sense?",
        'parent_five_minute'=>'Use paper strips, measuring cups, or a food item to model the lesson fraction. Have your child label the whole, partition equal parts, write the matching fraction, and explain one equivalent or operation step.',
        'teacher_objectives'=>"Students will represent fractions with accurate area, set, and number-line models.\nStudents will calculate with grade-appropriate fraction strategies.\nStudents will justify equivalence, comparison, or operations using precise vocabulary.",
        'teacher_pacing'=>"Launch | 5 minutes | Establish the whole with a familiar context.\nLearn It | 10 minutes | Connect an equal-part visual to notation.\nWorked Example | 8 minutes | Explain why every step preserves value.\nGuided Practice | 12 minutes | Release one labeled step at a time.\nIndependent Practice | 12 minutes | Require a model, equation, and check.\nMastery | 5 minutes | Check concepts, vocabulary, and transfer.",
        'teacher_misconceptions'=>"Students count unequal pieces as fractional parts | Repartition the same whole into equal parts.\nStudents compare only numerators or denominators | Use same-whole models and benchmarks.\nStudents apply whole-number operation rules to fractions | Name the fractional unit before operating.\nStudents simplify without preserving value | Connect every factor change to an equivalent model.",
        'teacher_differentiation'=>"Beginning | Use concrete fraction strips and unit fractions.\nDeveloping | Pair area models with number lines and equations.\nOn Level | Move flexibly among models, notation, and context.\nAdvanced | Generalize equivalence and operation rules with variables.\nMultilingual Learners | Pair vocabulary with labeled visuals, gestures, and sentence frames.",
        'teacher_formative'=>"Ask students to name the whole and the unit fraction.\nCheck that every visual has equal parts and matches the equation.\nListen for the meaning of numerator and denominator in context.\nUse one benchmark estimate and one transfer problem as an exit check.",
        'standards'=>'CCSS.MATH.CONTENT.'.$item['standard'].' — '.$item['grade'].' Number & Operations—Fractions.\nStandards for Mathematical Practice: SMP 1, SMP 2, SMP 3, SMP 4, SMP 6, and SMP 7.'
    ];
};

return array_map($expand, $lessons);
