<?php
if (!defined('ABSPATH')) exit;

/* Complete Kindergarten–Grade 8 Geometry lesson set. */
$seeds = [
 'k-identify-and-describe-shapes'=>['Identify and Describe Shapes','Kindergarten','K.G.A.1–3','name and describe two- and three-dimensional shapes','A triangle has 3 straight sides and 3 vertices | Trace each side. | Count the sides and vertices. | The shape is a triangle.','Which shape has no straight sides: a circle or a square? | circle','A shape has 4 equal sides and 4 vertices. What shape could it be? | square','Draw a triangle and label its 3 sides. | triangle'],
 'k-compose-shapes'=>['Compose Shapes','Kindergarten','K.G.B.4–6','build larger shapes from smaller shapes','Make a square with 2 equal triangles | Turn the triangles so their equal sides meet. | Slide them together without gaps. | The outside boundary forms a square.','Two half-circles join to make what shape? | circle','Use 2 equal rectangles to make one larger rectangle. How many small rectangles are used? | 2','Draw two shapes that can be joined to make a larger shape. | Answers vary'],
 '1-two-and-three-dimensional-shapes'=>['Two- and Three-Dimensional Shapes','Grade 1','1.G.A.1–2','distinguish and build two- and three-dimensional shapes','Sort a square and a cube | A square is flat and has 4 sides. | A cube is solid and has 6 square faces. | The square is 2D; the cube is 3D.','Is a sphere flat or solid? | solid','Which solid has 6 square faces? | cube','Draw one 2D shape and one 3D shape and name them. | Answers vary'],
 '1-partition-shapes-into-equal-shares'=>['Partition Shapes into Equal Shares','Grade 1','1.G.A.3','divide circles and rectangles into equal shares','Split a rectangle into 2 equal shares | Draw a line through the middle. | Check that both parts are the same size. | Each share is one half.','A circle is split into 4 equal parts. What is each part called? | one fourth','How many halves make one whole? | 2','Draw a rectangle partitioned into fourths. | 4 equal parts'],
 '2-reason-with-shapes'=>['Reason with Shapes','Grade 2','2.G.A.1','recognize shapes by their defining attributes','Classify a shape with 4 sides and 4 right angles | Count 4 sides. | Check all 4 angles are right angles. | It is a rectangle.','How many sides does a pentagon have? | 5','A shape has 3 sides. What is it? | triangle','Draw a quadrilateral and mark its 4 sides. | quadrilateral'],
 '2-partition-rectangles-and-circles'=>['Partition Rectangles and Circles','Grade 2','2.G.A.2–3','partition rectangles into rows and columns and shapes into equal shares','Partition a rectangle into 3 rows and 4 columns | Draw 3 equal rows. | Draw 4 equal columns. | There are 3 × 4 = 12 equal squares.','A rectangle has 2 rows of 5 squares. How many squares? | 10','A circle is split into 3 equal shares. What is each share called? | one third','Draw a 4-by-3 rectangular array. | 12 squares'],
 '3-classify-quadrilaterals'=>['Classify Quadrilaterals','Grade 3','3.G.A.1','classify quadrilaterals using sides and angles','Classify a square | It has 4 sides and 4 right angles, so it is a rectangle. | All 4 sides are equal, so it is also a rhombus. | A square belongs to both groups.','Is every square a rectangle? | yes','Which quadrilateral has exactly one pair of parallel sides? | trapezoid','Draw a quadrilateral hierarchy that includes squares and rectangles. | Answers vary'],
 '4-angles-and-angle-measurement'=>['Angles and Angle Measurement','Grade 4','4.G.A.1–3; 4.MD.C.5–7','identify and measure angles in degrees','Find a missing angle when 65° and the unknown make 125° | Write 65 + x = 125. | Subtract 65 from 125. | x = 60°.','Is a 35° angle acute, right, or obtuse? | acute','Two adjacent angles make 90°. One is 28°. Find the other. | 62°','Draw and label an obtuse angle. | Answers vary'],
 '4-lines-symmetry-and-shape-classification'=>['Lines, Symmetry, and Shape Classification','Grade 4','4.G.A.1–3','identify lines, angles, symmetry, and shape categories','Find lines of symmetry in a square | Fold through the vertical middle. | Repeat horizontally and along both diagonals. | A square has 4 lines of symmetry.','How many lines of symmetry does a non-square rectangle have? | 2','Are opposite sides of a rectangle parallel? | yes','Draw a shape with exactly one line of symmetry. | Answers vary'],
 '5-coordinate-plane'=>['Coordinate Plane','Grade 5','5.G.A.1–2','plot and interpret points in the first quadrant','Plot (4,3) | Start at the origin. | Move 4 units right on the x-axis. | Move 3 units up and mark the point.','Which coordinate tells the horizontal movement in (6,2)? | 6','Plot (2,5). How far above the x-axis is it? | 5 units','Draw a coordinate plane and plot three labeled points. | Answers vary'],
 '5-classify-two-dimensional-figures'=>['Classify Two-Dimensional Figures','Grade 5','5.G.B.3–4','organize two-dimensional figures in a hierarchy','Place squares in a shape hierarchy | Every square is a rhombus and rectangle. | Every rhombus and rectangle is a parallelogram. | Therefore every square is a parallelogram.','Is every rectangle a parallelogram? | yes','Is every parallelogram a rectangle? | no','Create a hierarchy for quadrilaterals and explain one relationship. | Answers vary'],
 '6-area-and-surface-area'=>['Area and Surface Area','Grade 6','6.G.A.1,4','find area of polygons and surface area from nets','Find the area of a triangle with base 8 and height 5 | Use A = 1/2 bh. | Substitute 8 and 5. | A = 20 square units.','Find the area of a triangle with base 10 and height 6. | 30 square units','A rectangular prism has faces with areas 12, 12, 8, 8, 6, and 6. Find its surface area. | 52 square units','Draw a prism net and label the area of every face. | Answers vary'],
 '6-volume'=>['Volume','Grade 6','6.G.A.2','find volume of rectangular prisms including fractional edges','Find the volume of a prism 4 by 3 by 2.5 | Use V = lwh. | Multiply 4 × 3 × 2.5. | V = 30 cubic units.','Find the volume of a 5-by-4-by-3 prism. | 60 cubic units','A prism has volume 48, length 4, and width 3. Find its height. | 4 units','Design two different prisms with the same volume. | Answers vary'],
 '7-scale-drawings'=>['Scale Drawings','Grade 7','7.G.A.1','use scale factors to find actual and drawing lengths','A map uses 1 cm = 4 m. A wall is 6 cm on the map | Multiply 6 by 4. | Keep the actual unit, meters. | The wall is 24 m long.','A drawing uses 1 inch = 5 feet. What does 7 inches represent? | 35 feet','A 30-foot room is drawn with 1 inch = 6 feet. How long is the drawing? | 5 inches','Make a scale drawing of a rectangular room. | Answers vary'],
 '7-circles'=>['Circles','Grade 7','7.G.B.4','use radius, diameter, circumference, and area','Find the circumference of a circle with radius 5 | Use C = 2πr. | Substitute r = 5. | C = 10π units.','A circle has diameter 12. What is its radius? | 6','Find the area of a circle with radius 4. | 16π square units','Draw a circle and label its center, radius, and diameter. | Answers vary'],
 '7-angle-relationships'=>['Angle Relationships','Grade 7','7.G.B.5','solve problems with complementary, supplementary, vertical, and adjacent angles','One angle in a vertical pair is 72° | Vertical angles are congruent. | The opposite angle has the same measure. | The missing angle is 72°.','Two supplementary angles include 118°. Find the other. | 62°','Two complementary angles include 37°. Find the other. | 53°','Draw intersecting lines and label a vertical angle pair. | Answers vary'],
 '7-area-surface-area-and-volume'=>['Area, Surface Area, and Volume','Grade 7','7.G.B.6','solve real-world problems involving 2D and 3D measures','Find the area of a 12-by-8 rectangle with a 4-by-3 corner removed | Find 12 × 8 = 96. | Find 4 × 3 = 12. | Subtract: 96 − 12 = 84 square units.','Find the area of a parallelogram with base 9 and height 7. | 63 square units','Find the volume of a 6-by-5-by-4 prism. | 120 cubic units','Design a composite figure and find its area or volume. | Answers vary'],
 '8-transformations'=>['Transformations','Grade 8','8.G.A.1–3','describe translations, reflections, rotations, and dilations','Translate point (2,3) right 4 and up 1 | Add 4 to x. | Add 1 to y. | The image is (6,4).','Reflect (5,−2) across the x-axis. | (5,2)','Rotate (3,1) 90° counterclockwise about the origin. | (−1,3)','Draw a polygon and its translated image on a coordinate plane. | Answers vary'],
 '8-congruence-and-similarity'=>['Congruence and Similarity','Grade 8','8.G.A.2–5','use transformations to explain congruence and similarity','Dilate a triangle by scale factor 2 | Multiply every distance from the center by 2. | Angle measures stay the same. | Side lengths double, so the image is similar.','Are two figures congruent after a translation? | yes','A side of 6 is dilated by 1.5. What is the image length? | 9','Explain a transformation sequence that maps one figure to another. | Answers vary'],
 '8-pythagorean-theorem-and-distance'=>['Pythagorean Theorem and Distance','Grade 8','8.G.B.6–8','use the Pythagorean Theorem to find lengths and distances','A right triangle has legs 6 and 8 | Write 6² + 8² = c². | Simplify: 36 + 64 = 100. | c = √100 = 10 units.','Find the hypotenuse with legs 5 and 12. | 13','Find the distance between (0,0) and (6,8). | 10','Create a coordinate distance problem and solve it. | Answers vary'],
 '8-volume-cylinders-cones-and-spheres'=>['Volume of Cylinders, Cones, and Spheres','Grade 8','8.G.C.9','use volume formulas for cylinders, cones, and spheres','Find the volume of a cylinder with radius 3 and height 5 | Use V = πr²h. | Substitute 3 and 5. | V = 45π cubic units.','Find the volume of a cone with radius 3 and height 4. | 12π cubic units','Find the volume of a sphere with radius 3. | 36π cubic units','Compare a cylinder and cone with the same radius and height. | The cone has one third the volume'],
];

$video = 'https://www.youtube.com/watch?v=zF5Axl2mFnc';
$out = [];
foreach ($seeds as $slug => $v) {
 [$title,$grade,$standard,$focus,$example,$warm,$guided,$independent] = $v;
 $practice = function($raw,$directions) { [$q,$a] = array_map('trim',explode('|',$raw,2)); return $directions.' || '.$q.' | '.$a.' | Identify the given geometric information and what you need to find. | Draw or label a matching figure before choosing a rule. | Use the labeled figure, apply the correct definition or formula, solve step by step, include units when needed, and check the result.'; };
 $out[$slug] = [
  'title'=>$title,'subtitle'=>'Use precise geometric language, diagrams, and reasoning to '.$focus.'.','essential_question'=>'How can a labeled geometric model help us '.$focus.'?',
  'learning_targets'=>"I can name and label the important parts of a geometric figure.\nI can choose a definition, property, transformation, or formula that fits.\nI can use a diagram to explain and check my result.",
  'vocabulary'=>"geometry — the study of shapes, space, position, and measurement\nattribute — a feature used to describe or classify a figure\nvertex — a point where sides or edges meet\nangle — a figure made by two rays with the same endpoint\ncongruent — exactly the same size and shape\nsimilar — the same shape with proportional side lengths",
  'worked_examples'=>$example,
  'common_mistakes'=>"Using a picture that does not match the question | Label every given length, angle, point, and shape.\nChoosing a rule before identifying the figure | Name the shape and what is known first.\nMixing area, surface area, and volume | Use square units for area and cubic units for volume.\nAssuming a drawing is to scale | Use the stated measurements and markings, not appearance alone.",
  'real_life'=>'Geometry helps people create maps, buildings, art, computer graphics, packaging, sports plans, and accurate measurements.',
  'videos'=>$title.' | '.$video,'video_chapters'=>"0:00 | Name the figure and its parts\n1:00 | Read the labels and markings\n2:15 | Choose a definition, property, or formula\n3:30 | Solve and check with the diagram",
  'practice_warmup'=>$practice($warm,'Study the figure. Label what is given, name the geometric idea you will use, show your work, and enter the final answer.'),
  'guided_practice'=>$practice($guided,'Follow the steps. Draw or inspect the matching figure, label every known value, choose the geometric rule, and solve.'),
  'independent_practice'=>$practice($independent,'Work independently. Make a matching diagram, show each reasoning step, include units when needed, and enter the final answer.'),
  'challenge_practice'=>$practice('Create a new problem that asks someone to '.$focus.'. Include a precise labeled diagram, solve it, and explain how the picture proves the result. | Answers vary','Create and solve your own geometry problem. Make every part of the visual match the question.'),
  'master_it'=>"I can use correct geometric vocabulary.\nI can make a diagram that matches every part of a problem.\nI can justify a classification, measurement, or transformation.",
  'mastery_questions'=>"What should a useful geometry diagram include? | Labels and markings that match the problem ; Unrelated decorations ; An answer only ; No measurements | A\nWhat do congruent figures have? | The same size and shape ; Only the same color ; Different angle measures ; No matching parts | A\nWhich units describe area? | Square units ; Cubic units ; Degrees only ; Units per hour | A\nWhat should you do before selecting a formula? | Identify the figure, known values, and unknown ; Guess the answer ; Erase the labels ; Change the dimensions | A\nHow can a diagram help check an answer? | It shows whether the result fits the figure and given measures ; It changes the formula ; It removes all units ; It guarantees every estimate is exact | A",
  'parent_summary'=>'Students use accurate pictures, vocabulary, properties, transformations, coordinates, and formulas to describe and solve geometry problems.','parent_conversation'=>"Ask: What shape or figure do you see?\nAsk: Which labels and markings matter?\nAsk: How does the diagram support the answer?",'parent_five_minute'=>'Find a household shape or sketch a simple figure. Have your child name its attributes, add labels, ask one question about it, and explain the answer.',
  'teacher_objectives'=>"Students will represent geometric situations with accurate labeled models.\nStudents will apply grade-appropriate definitions, properties, transformations, and formulas.\nStudents will justify conclusions with diagrams and mathematical language.",
  'teacher_pacing'=>"Launch | 5 minutes | Connect the figure to a familiar object or movement.\nLearn It | 10 minutes | Read a completed visual model.\nWorked Example | 8 minutes | Explain every label and reasoning step.\nGuided Practice | 12 minutes | Reveal one decision at a time.\nIndependent Practice | 12 minutes | Require a matching diagram and explanation.\nMastery | 5 minutes | Check vocabulary, reasoning, and transfer.",
  'teacher_misconceptions'=>"Students classify by appearance alone | Require defining attributes and markings.\nStudents confuse 2D and 3D measures | Connect length, square units, and cubic units to the model.\nStudents reverse coordinate order | Say x first, then y, and trace each movement.\nStudents use a generic visual | Match every object, number, angle, and relationship to the prompt.",
  'teacher_differentiation'=>"Beginning | Build with physical shapes, tiles, nets, and tracing paper.\nDeveloping | Pair each vocabulary word with a color-coded diagram.\nOn Level | Connect words, diagrams, equations, and justifications.\nAdvanced | Add constraints, composite figures, or multiple transformation steps.\nMultilingual Learners | Use gestures and labeled visuals for position, direction, and attributes.",
  'teacher_formative'=>"Check that the diagram represents the exact question.\nAsk students to name the defining property or formula before calculating.\nListen for correct use of sides, vertices, angles, faces, congruent, and similar.\nUse one visual transfer problem as an exit check.",
  'standards'=>'CCSS.MATH.CONTENT.'.$standard.' — '.$grade.' Geometry.\nStandards for Mathematical Practice: SMP 1, SMP 2, SMP 3, SMP 4, SMP 5, and SMP 6.'
 ];
}
return $out;
