<?php
/** Canonical 24-field content for inequalities and triangles/transformations. */
if (!defined('ABSPATH')) exit;

$build = static function ($title, $subtitle, $question, $targets, $vocabulary, $examples, $mistakes, $real_life, $video_url, $warmup, $guided, $independent, $challenge, $mastery, $standards) {
    return [
        'title' => $title,
        'subtitle' => $subtitle,
        'essential_question' => $question,
        'learning_targets' => $targets,
        'vocabulary' => $vocabulary,
        'worked_examples' => $examples,
        'common_mistakes' => $mistakes,
        'real_life' => $real_life,
        'videos' => $title . ' lesson and examples | ' . $video_url,
        'video_chapters' => "0:00 | Connect to prior knowledge\n1:20 | Model the core idea\n3:00 | Work an example\n4:45 | Analyze a common error\n6:00 | Try and check",
        'practice_warmup' => $warmup,
        'guided_practice' => $guided,
        'independent_practice' => $independent,
        'challenge_practice' => $challenge,
        'master_it' => $mastery,
        'mastery_questions' => "Which statement shows the key idea in this lesson? | A correct model ; An unrelated fact ; A reversed rule ; An unsupported guess | A\nWhich habit best supports accuracy? | Skip the diagram ; Label known information ; Ignore units ; Round first | B\nWhat should a student do after solving? | Check the result ; Erase the work ; Change the question ; Choose a larger answer | A\nWhich explanation is strongest? | An answer only ; A labeled model with reasoning ; A guess ; A copied rule | B\nHow can an error be found? | Compare each step with the definition or theorem ; Hide the steps ; Change all signs ; Use no labels | A",
        'parent_summary' => 'In ' . $title . ', students connect definitions, visual models, and symbolic reasoning. Accuracy comes from labeling information, showing each step, and checking whether the result fits the original situation.',
        'parent_conversation' => "Ask: What information is given and what must be found?\nAsk: Which definition, rule, or theorem supports that step?\nAsk your child to show a second way to check the result.",
        'parent_five_minute' => 'Draw or write one simple ' . strtolower($title) . ' example together. Have your child label the known information, explain one step aloud, and verify the result.',
        'teacher_objectives' => "Students will represent " . strtolower($title) . " with accurate mathematical notation and visual models.\nStudents will justify procedures with definitions, properties, or theorems.\nStudents will check solutions and explain errors.",
        'teacher_pacing' => "Launch | 5 minutes | Use a visual notice-and-wonder prompt.\nLearn It | 15 minutes | Model vocabulary and reasoning.\nWatch It | 7 minutes | Pause for predictions.\nPractice It | 20 minutes | Move from guided to independent work.\nMastery | 8 minutes | Require a labeled check or justification.",
        'teacher_misconceptions' => $mistakes,
        'teacher_differentiation' => "Below Level | Use color-coded diagrams, manipulatives, and partially completed examples.\nOn Level | Mix representations and require written reasoning.\nAdvanced | Add proof, reverse reasoning, or multi-step applications.\nMultilingual Learners | Pair vocabulary with symbols, gestures, diagrams, and sentence frames.",
        'teacher_formative' => "Listen for precise vocabulary during partner explanations.\nUse one error-analysis prompt during guided practice.\nCollect an exit ticket requiring an answer, supporting work, and a check.",
        'standards' => $standards,
    ];
};

return [
    'solving-linear-inequalities' => $build(
        'Solving Linear Inequalities',
        'Solve linear inequalities and represent every value in the solution set.',
        'How can inverse operations isolate a variable without changing the meaning of an inequality?',
        "I can solve one-step and multi-step linear inequalities.\nI can reverse the inequality symbol when multiplying or dividing by a negative.\nI can check whether values belong to a solution set.",
        "Inequality — a comparison using <, >, ≤, or ≥\nSolution set — all values that make an inequality true\nBoundary point — the endpoint separating solutions from nonsolutions\nInverse operations — operations that undo one another",
        "Solve 3x+4<19 | Subtract 4, then divide by 3. | 3x<15. | x<5.\nSolve −2x+7≥15 | Subtract 7, then divide by −2 and reverse the symbol. | −2x≥8. | x≤−4.",
        "Forgetting to reverse the symbol after division by a negative | Compare a true number sentence before and after multiplying by −1.\nTreating the answer as one value | Test several values from the solution side.\nReversing the symbol when adding a negative | Reverse only for multiplication or division by a negative.",
        'Inequalities describe budgets, minimum ages, capacity limits, target ranges, and values that must stay above or below a threshold.',
        'https://www.khanacademy.org/math/cc-seventh-grade-math/cc-7th-variables-expressions/cc-7th-2-step-inequalities',
        'Solve x+6>10. | x>4 | Subtract 6 from both sides. | Check 5: 5+6>10 is true.',
        "Solve 5x≤30. | x≤6 | Divide both sides by 5. | Check 6 and 7.\nSolve 12−3x>21. | x<−3 | Subtract 12, divide by −3, and reverse the symbol. | Check −4.",
        "Solve 4x−9≥19. | x≥7 | Add 9 and divide by 4.\nSolve −5(x−2)<20. | x>−2 | Divide by −5, reverse, then add 2.\nSolve 3x+8≤x−4. | x≤−6 | Collect variable terms and solve.",
        'Create a real situation modeled by −4x+18≥42. Solve it, graph the solution, and explain why the symbol reverses.',
        "I can keep both sides equivalent at every step.\nI reverse the symbol only after multiplying or dividing by a negative.\nI can verify boundary and interior values.",
        "CCSS.MATH.CONTENT.6.EE.B.8 — Write and represent inequalities.\nCCSS.MATH.CONTENT.7.EE.B.4.B — Solve word problems leading to inequalities.\nCCSS.MATH.PRACTICE.MP1, MP3, and MP6 — Persevere, justify, and attend to precision."
    ),
    'graphing-linear-inequalities' => $build(
        'Graphing Linear Inequalities',
        'Display solution sets on number lines and coordinate planes.',
        'How does a graph show all ordered pairs or values that satisfy an inequality?',
        "I can graph one-variable inequalities with correct endpoints and shading.\nI can graph two-variable linear inequalities using a boundary line and test point.\nI can interpret overlapping solution regions.",
        "Open circle — endpoint not included\nClosed circle — endpoint included\nBoundary line — line separating solution and nonsolution regions\nTest point — point used to determine which half-plane to shade\nSolution region — all points satisfying the inequality",
        "Graph x≤3 | Place a closed circle at 3. | Shade left because values are less than 3. | Include 3.\nGraph y>2x−1 | Draw y=2x−1 as a dashed line. | Test (0,0): 0>−1 is true. | Shade the side containing (0,0).",
        "Using an open circle for ≤ or ≥ | Equal means the boundary is included.\nDrawing a solid boundary for < or > | Strict inequalities exclude the boundary.\nShading from the slope alone | Test a point not on the boundary.",
        'Graphical inequalities model safe operating ranges, spending limits, feasible design regions, and combinations that meet multiple constraints.',
        'https://www.khanacademy.org/math/algebra/x2f8bb11595b61c86:inequalities-systems-graphs',
        'Graph x>−2. | Open circle at −2, shade right | The boundary is excluded and greater values lie right.',
        "Graph y≤x+2. | Solid line; shade the side containing (0,0) | Test gives 0≤2.\nGraph y<−2x+4. | Dashed boundary; shade below | A point such as (0,0) satisfies it.",
        "Graph x≥1 and x<5 on one number line. | [1,5) | Use closed at 1 and open at 5.\nGraph y≥3x−2. | Solid boundary, correct half-plane | Test (0,0).\nDetermine whether (2,1) satisfies y<−x+4. | Yes | 1<2.",
        'Graph y≥x−3 and y<−2x+6 together. Identify two points in the overlap and verify both inequalities algebraically.',
        "I choose open or closed boundaries from the symbol.\nI use a test point to determine shading.\nI verify points by substitution.",
        "CCSS.MATH.CONTENT.6.EE.B.8 — Represent solutions on number lines.\nCCSS.MATH.CONTENT.HSA.REI.D.12 — Graph linear inequalities in two variables.\nCCSS.MATH.PRACTICE.MP2, MP4, and MP6 — Reason, model, and attend to precision."
    ),
    'transformations' => $build(
        'Transformations', 'Describe translations, reflections, rotations, and dilations on the coordinate plane.',
        'How do transformation rules predict the location and size of an image?',
        "I can identify and perform translations, reflections, rotations, and dilations.\nI can write coordinate rules for transformations.\nI can distinguish rigid motions from transformations that change size.",
        "Preimage — original figure\nImage — transformed figure\nTranslation — slide\nReflection — flip across a line\nRotation — turn about a center\nDilation — size change from a center by a scale factor",
        "Translate (−2,3) right 5 and down 1 | Add (5,−1). | Image is (3,2).\nRotate (4,−1) 90° counterclockwise about the origin | Use (x,y)→(−y,x). | Image is (1,4).",
        "Changing coordinate signs without using the correct rule | State the transformation and rule first.\nConfusing the preimage and image | Use unprimed and primed labels.\nAssuming every transformation preserves size | Dilations change size unless the scale factor is 1.",
        'Transformations appear in animation, art, architecture, maps, robotics, computer graphics, and repeating designs.',
        'https://www.khanacademy.org/math/cc-eighth-grade-math/geometric-transformations',
        'Translate (1,−2) by ⟨3,4⟩. | (4,2) | Add the vector components.',
        "Reflect (3,−5) across the x-axis. | (3,5) | Use (x,y)→(x,−y).\nRotate (−2,4) 180° about the origin. | (2,−4) | Negate both coordinates.",
        "Reflect (−6,2) across y=x. | (2,−6) | Swap coordinates.\nDilate (4,−2) by factor 1/2 from the origin. | (2,−1) | Multiply both coordinates.\nDescribe the change from (1,2) to (−2,1). | 90° counterclockwise rotation | Apply the rule.",
        'Design a four-step transformation sequence that returns a nonsymmetric triangle to its original location. Record and verify every coordinate rule.',
        "I can name the transformation from its coordinate changes.\nI apply the rule to every vertex.\nI check preserved lengths, angles, orientation, or scale as appropriate.",
        "CCSS.MATH.CONTENT.8.G.A.1–4 — Verify properties and describe transformation sequences.\nCCSS.MATH.CONTENT.HSG.CO.A.2–5 — Represent and compare transformations.\nCCSS.MATH.PRACTICE.MP4 and MP6 — Model and attend to precision."
    ),
    'congruence-and-rigid-motions' => $build(
        'Congruence and Rigid Motions', 'Use rigid-motion sequences to establish and explain congruence.',
        'Why do translations, rotations, and reflections preserve congruence?',
        "I can identify corresponding parts of congruent figures.\nI can describe a rigid-motion sequence mapping one figure onto another.\nI can use congruence criteria to justify triangle congruence.",
        "Congruent — same size and shape\nRigid motion — transformation preserving distance and angle measure\nCorresponding parts — matching sides and angles\nSSS, SAS, ASA, AAS, HL — triangle congruence criteria",
        "Triangle ABC maps onto A′B′C′ by a translation | Corresponding distances and angles remain equal. | The triangles are congruent.\nTwo right triangles have equal hypotenuse and one equal leg | Apply HL. | The triangles are congruent.",
        "Using AAA to prove congruence | AAA proves similarity, not equal size.\nMatching vertices out of order | Write congruence statements from corresponding positions.\nIncluding a dilation with scale factor not 1 | It is not a rigid motion.",
        'Congruence supports manufacturing tolerances, pattern cutting, construction, quality control, and repeatable computer graphics.',
        'https://www.khanacademy.org/math/geometry/hs-geo-congruence',
        'Are two figures related by a reflection congruent? | Yes | Reflections preserve distance and angle measure.',
        "Name a criterion for three equal side pairs. | SSS | All corresponding sides match.\nMap a figure using a rotation then translation. | A rigid sequence | Both motions preserve congruence.",
        "Decide whether SAS data proves congruence. | Yes, when the angle is included | Identify the two sides and included angle.\nExplain why SSA is generally insufficient. | It can form different triangles | Sketch the ambiguous case.\nWrite a correct correspondence statement. | Match equal angles and sides | Keep vertex order consistent.",
        'Create two congruent triangles in different orientations. Give a minimum rigid-motion sequence and a second valid sequence mapping one to the other.',
        "I match corresponding vertices accurately.\nI distinguish rigid motions from dilations.\nI cite an appropriate congruence criterion and supporting evidence.",
        "CCSS.MATH.CONTENT.8.G.A.2 — Understand congruence through rigid motions.\nCCSS.MATH.CONTENT.HSG.CO.B.6–8 — Use transformations and triangle criteria.\nCCSS.MATH.PRACTICE.MP3 and MP6 — Construct arguments and attend to precision."
    ),
    'similarity-and-dilations' => $build(
        'Similarity and Dilations', 'Use scale factors and transformations to analyze similar figures.',
        'How does a dilation change lengths while preserving angle measures and shape?',
        "I can dilate a figure from a center using a scale factor.\nI can determine whether figures are similar.\nI can solve for missing lengths with proportional relationships.",
        "Similar — same shape with proportional corresponding lengths\nScale factor — multiplier relating image and preimage lengths\nCenter of dilation — fixed point from which distances scale\nAA similarity — two corresponding angles are equal",
        "Dilate (6,−3) from the origin by 2/3 | Multiply coordinates by 2/3. | Image is (4,−2).\nSimilar triangles have sides 6 and 9 corresponding to 10 and x | 6/10=9/x. | x=15.",
        "Adding the scale factor instead of multiplying | A dilation multiplies distances from the center.\nUsing noncorresponding sides in proportions | Mark matching angles first.\nAssuming similar means congruent | Congruence requires scale factor 1.",
        'Similarity is used in maps, models, blueprints, photography, indirect measurement, and resizing digital images.',
        'https://www.khanacademy.org/math/geometry/hs-geo-similarity',
        'A side of 8 is dilated by 1.5. | 12 | Multiply 8 by 1.5.',
        "Find x if 4/10=6/x. | 15 | Cross multiply.\nDilate (−3,5) by 2 from the origin. | (−6,10) | Multiply each coordinate.",
        "Are 3-4-5 and 6-8-10 triangles similar? | Yes | Each side scale factor is 2.\nFind a missing side when scale factor is 3/4. | Multiply the corresponding length | Preserve correspondence.\nExplain AA similarity. | Two equal angle pairs force the third pair and shape | Sizes may differ.",
        'Use a mirror or shadow method to estimate an inaccessible height. Draw similar triangles, collect plausible measurements, and justify the proportion.',
        "I identify corresponding parts before forming ratios.\nI apply the scale factor consistently.\nI verify equal angles and proportional side lengths.",
        "CCSS.MATH.CONTENT.8.G.A.3–4 — Describe dilations and understand similarity.\nCCSS.MATH.CONTENT.HSG.SRT.A.1–3 — Verify dilation properties and establish similarity.\nCCSS.MATH.PRACTICE.MP2 and MP4 — Reason and model."
    ),
    'triangle-angle-relationships' => $build(
        'Triangle Angle Relationships', 'Use interior, exterior, and inequality relationships to reason about triangles.',
        'How do angle and side relationships determine what triangles are possible?',
        "I can use the triangle angle-sum and exterior-angle theorems.\nI can relate larger angles to longer opposite sides.\nI can apply the triangle inequality theorem.",
        "Interior angle — angle inside a polygon\nExterior angle — angle formed by a side and an extended adjacent side\nRemote interior angles — two nonadjacent interior angles\nTriangle inequality — sum of any two side lengths exceeds the third",
        "Triangle angles are 48°, 67°, and x | x=180−115=65°.\nAn exterior angle is 124° and one remote interior angle is 53° | Other remote angle is 71°.",
        "Subtracting an exterior angle from 180 without identifying the target | Mark adjacent and remote angles.\nPairing the largest angle with the shortest side | Larger angles face longer sides.\nUsing ≥ in triangle inequality | The sum must be strictly greater.",
        'Triangle relationships help engineers check structural braces, surveyors calculate directions, and designers verify that dimensions can form a stable triangle.',
        'https://www.khanacademy.org/math/geometry/hs-geo-foundations/hs-geo-angles',
        'Find the third angle if two angles are 35° and 80°. | 65° | Subtract their sum from 180°.',
        "Exterior angle 140° has one remote angle 55°. Find the other. | 85° | Subtract 55 from 140.\nCan 3,4,8 form a triangle? | No | 3+4 is not greater than 8.",
        "Order sides opposite 40°, 60°, 80°. | Increasing with the angles | Larger angles face longer sides.\nFind x in angles x, 2x, and 3x. | 30 | 6x=180.\nChoose a possible third side with sides 7 and 12. | Any value between 5 and 19 | Use difference and sum bounds.",
        'Create a triangle constraint puzzle using angle sum, exterior angle, and triangle inequality. Solve it and explain why no alternate triangle satisfies all clues.',
        "I use 180° for interior angle sum.\nI connect an exterior angle to its two remote interior angles.\nI test all required side-sum inequalities.",
        "CCSS.MATH.CONTENT.8.G.A.5 — Use angle relationships in triangles.\nCCSS.MATH.CONTENT.HSG.CO.C.10 — Prove triangle theorems.\nCCSS.MATH.PRACTICE.MP3 and MP7 — Argue and use structure."
    ),
    'pythagorean-theorem-and-distance-formula' => $build(
        'Pythagorean Theorem and Distance Formula', 'Find unknown right-triangle lengths and distances on the coordinate plane.',
        'How does the Pythagorean Theorem connect right triangles to coordinate distance?',
        "I can identify legs and hypotenuse in a right triangle.\nI can solve contextual problems using a²+b²=c².\nI can use the distance formula and its converse.",
        "Legs — sides forming the right angle\nHypotenuse — side opposite the right angle\nPythagorean Theorem — a²+b²=c²\nConverse — test showing whether side lengths form a right triangle\nDistance formula — coordinate form of the theorem",
        "Legs 6 and 8 | c²=36+64=100. | c=10.\nDistance from (−1,2) to (3,5) | Changes are 4 and 3. | d=√(4²+3²)=5.",
        "Using the hypotenuse as a leg | Locate the side opposite the right angle.\nForgetting the square root | c² is not c.\nSubtracting coordinates inconsistently | Keep the same endpoint order; squares remove signs.",
        'The theorem is used in construction, navigation, screen dimensions, ramps, ladders, surveying, and straight-line map distance.',
        'https://www.khanacademy.org/math/cc-eighth-grade-math/cc-8th-geometry/cc-8th-pythagorean-theorem',
        'Find the hypotenuse with legs 5 and 12. | 13 | 25+144=169 and √169=13.',
        "Find a leg if c=10 and the other leg is 6. | 8 | b²=100−36=64.\nFind distance from (0,0) to (8,15). | 17 | √(64+225).",
        "Do 7,24,25 form a right triangle? | Yes | 49+576=625.\nFind the diagonal of a 9 by 12 rectangle. | 15 | Apply the theorem.\nFind distance from (−2,−1) to (4,7). | 10 | Changes are 6 and 8.",
        'Compare two routes across a rectangular park: along two sides and directly across. Calculate both, include units, and explain the practical tradeoff.',
        "I identify the hypotenuse before substituting.\nI square, combine, and take the principal square root.\nI estimate to check whether the length is reasonable.",
        "CCSS.MATH.CONTENT.8.G.B.6–8 — Explain and apply the Pythagorean Theorem and find coordinate distance.\nCCSS.MATH.PRACTICE.MP1, MP4, and MP6 — Persevere, model, and attend to precision."
    ),
    'right-triangle-trigonometry' => $build(
        'Right-Triangle Trigonometry', 'Use sine, cosine, and tangent ratios to solve right triangles.',
        'How do side ratios connect an acute angle to every similar right triangle?',
        "I can label opposite, adjacent, and hypotenuse relative to an angle.\nI can choose sine, cosine, or tangent to find a missing measure.\nI can use inverse trigonometric functions to find an angle.",
        "Sine — opposite/hypotenuse\nCosine — adjacent/hypotenuse\nTangent — opposite/adjacent\nAngle of elevation — angle measured upward from horizontal\nInverse trigonometric function — operation used to recover an angle",
        "Angle 35° and hypotenuse 12; find opposite side | sin35°=x/12. | x=12sin35°≈6.9.\nOpposite 9 and adjacent 12; find angle | tanθ=9/12. | θ=tan⁻¹(0.75)≈36.9°.",
        "Labeling sides without reference to the chosen angle | Circle the angle first.\nUsing degrees while calculator is in radians | Confirm degree mode.\nRounding during intermediate steps | Keep full precision until the final answer.",
        'Trigonometry supports surveying, aviation, architecture, astronomy, accessibility ramps, heights, slopes, and navigation.',
        'https://www.khanacademy.org/math/geometry/hs-geo-trig',
        'Relative to angle θ, which side is always longest? | Hypotenuse | It lies opposite the right angle.',
        "Given opposite 6 and hypotenuse 10, find sinθ. | 0.6 | Use opposite/hypotenuse.\nGiven adjacent 8 and hypotenuse 17, find cosθ. | 8/17 | Use adjacent/hypotenuse.",
        "Find opposite side when θ=40° and adjacent=11. | 11tan40°≈9.2 | Use tangent.\nFind θ when opposite=5 and hypotenuse=13. | sin⁻¹(5/13)≈22.6° | Use inverse sine.\nFind adjacent when θ=28° and hypotenuse=20. | 20cos28°≈17.7 | Use cosine.",
        'Plan an indirect height measurement for a flagpole. Choose a realistic horizontal distance and angle of elevation, calculate height, and describe sources of measurement error.',
        "I label sides relative to the selected angle.\nI choose the ratio containing the known and unknown quantities.\nI use degree mode, units, and sensible rounding.",
        "CCSS.MATH.CONTENT.HSG.SRT.C.6–8 — Define and use trigonometric ratios and solve right triangles.\nCCSS.MATH.PRACTICE.MP4, MP5, and MP6 — Model, use tools, and attend to precision."
    ),
    'geometric-constructions' => $build(
        'Geometric Constructions', 'Create exact geometric figures from definitions and justify every construction step.',
        'How can a compass and straightedge encode geometric definitions without measuring?',
        "I can construct perpendicular and angle bisectors.\nI can copy segments and angles and construct parallel or perpendicular lines.\nI can explain why a construction works.",
        "Compass — tool for transferring equal distances\nStraightedge — unmarked tool for drawing lines\nPerpendicular bisector — line through a midpoint at 90°\nAngle bisector — ray dividing an angle into equal angles\nLocus — set of points meeting a condition",
        "Construct a perpendicular bisector of AB | Draw equal-radius arcs from A and B that intersect above and below. | Connect intersections. | Every point on the line is equidistant from A and B.\nBisect an angle | Mark equal distances on both rays, then intersect equal-radius arcs. | Connect the vertex to the arc intersection.",
        "Changing compass width when equal radii are required | Lock or carefully preserve the opening.\nUsing visual estimation as proof | Cite equal-radius circles and congruent triangles.\nDrawing arcs too small to intersect | Use a radius greater than half the segment when bisecting.",
        'Constructions support drafting, machining, architecture, navigation, design, and the logical foundations of geometric software.',
        'https://www.khanacademy.org/math/geometry/hs-geo-congruence/hs-geo-constructions',
        'What tools define a classical construction? | Compass and unmarked straightedge | Measurements are transferred geometrically.',
        "Construct the midpoint of a segment. | Use its perpendicular bisector | The intersection divides it equally.\nCopy an angle. | Transfer one arc and the chord between ray intersections | Equal radii reproduce the opening.",
        "Construct a perpendicular through a point on a line. | Use two equidistant points and intersecting arcs | Connect the given point to the arc intersection.\nConstruct a parallel line through an outside point. | Copy a corresponding angle | Equal corresponding angles establish parallel lines.\nConstruct an inscribed regular hexagon. | Step the circle radius around the circumference | Six equal chords result.",
        'Construct the circumcenter of a triangle using two perpendicular bisectors. Explain why the point is equidistant from all three vertices and test it with a circle.',
        "I preserve required compass radii.\nI leave construction marks visible.\nI justify steps with loci, equal radii, congruence, or angle relationships.",
        "CCSS.MATH.CONTENT.HSG.CO.D.12–13 — Make formal geometric constructions.\nCCSS.MATH.PRACTICE.MP3, MP5, and MP6 — Justify, use tools, and attend to precision."
    ),
    'coordinate-geometry-and-proof' => $build(
        'Coordinate Geometry and Proof', 'Use coordinates, slope, midpoint, and distance to verify geometric relationships.',
        'How can algebraic calculations prove geometric facts about a figure?',
        "I can calculate slope, midpoint, and distance.\nI can prove lines are parallel or perpendicular from slopes.\nI can classify figures using coordinate evidence.",
        "Slope — rate of vertical change to horizontal change\nMidpoint — point halfway between endpoints\nDistance — length between points\nParallel — coplanar lines that do not intersect\nPerpendicular — lines meeting at right angles",
        "Endpoints (−2,3) and (6,7) | Midpoint=((−2+6)/2,(3+7)/2)=(2,5).\nSlopes of opposite sides are both 2/3 | The sides are parallel. | Equal slopes provide coordinate evidence.",
        "Using only the picture as proof | Calculate the needed slopes, distances, or midpoints.\nReversing subtraction order in one slope coordinate only | Use the same endpoint order.\nCalling negative slopes perpendicular | Their slopes must be negative reciprocals when defined.",
        'Coordinate proof is used in mapping, CAD, surveying, computer graphics, property layouts, and location-based systems.',
        'https://www.khanacademy.org/math/geometry/hs-geo-analytic-geometry',
        'Find midpoint of (2,4) and (8,10). | (5,7) | Average corresponding coordinates.',
        "Find slope through (1,2) and (5,10). | 2 | (10−2)/(5−1).\nAre slopes 3/4 and −4/3 perpendicular? | Yes | Their product is −1.",
        "Find distance from (−1,−2) to (2,2). | 5 | Changes are 3 and 4.\nProve a quadrilateral is a parallelogram. | Show both opposite-side slope pairs equal | Or show diagonals share a midpoint.\nClassify a triangle from three distances. | Compare side lengths and test the Pythagorean relationship | Cite the evidence.",
        'Choose four integer-coordinate vertices forming a non-axis-aligned rectangle. Prove it is a rectangle using slopes and distances, then calculate its area.',
        "I select calculations that directly support the claim.\nI show exact values before rounding.\nI state a conclusion tied to the coordinate evidence.",
        "CCSS.MATH.CONTENT.HSG.GPE.B.4–7 — Use coordinates to prove geometric theorems and compute measures.\nCCSS.MATH.PRACTICE.MP3, MP4, and MP6 — Argue, model, and attend to precision."
    ),
];
