<?php
if (!defined('ABSPATH')) exit;

/* Complete Kindergarten–Grade 5 Measurement & Data lesson set. */
$lessons = [
 'k-describe-and-compare-measurement'=>['Describe and Compare Measurement','Kindergarten','K.MD.A.1–2','compare measurable attributes such as length, height, and weight','Compare a 7-centimeter pencil and a 10-centimeter pencil | Line up both pencils at the same starting point. | Compare their endpoints. | The 10-centimeter pencil is 3 centimeters longer.','A ribbon is 6 cm long and another is 9 cm long. Which is longer? | 9 cm ribbon','A book is 4 cubes tall and a box is 7 cubes tall. How much taller is the box? | 3 cubes','Draw one object longer than a crayon and one object shorter than a crayon. | Answers vary'],
 'k-sort-and-classify-objects'=>['Sort and Classify Objects','Kindergarten','K.MD.B.3','sort objects into categories and count each category','Sort 8 buttons by shape | Look at one attribute: shape. | Put circles together and squares together. | Count each group and compare the totals.','Sort 3 triangles and 5 circles. Which category has more? | circles','There are 4 red blocks and 2 blue blocks. How many blocks are there altogether? | 6','Sort classroom objects by color, shape, or size and explain your rule. | Answers vary'],
 '1-measure-lengths'=>['Measure Lengths','Grade 1','1.MD.A.1–2','measure length with equal-size units placed end to end','Measure a pencil with 9 connecting cubes | Place the first cube at one end. | Put cubes end to end with no gaps or overlaps. | Count 9 cubes, so the pencil is 9 cubes long.','A marker is 7 cubes long. What is its length? | 7 cubes','A paper strip reaches from 0 to 12 on a centimeter ruler. How long is it? | 12 cm','Measure two objects with the same unit and find the difference. | Answers vary'],
 '1-time-to-the-hour-and-half-hour'=>['Time to the Hour and Half Hour','Grade 1','1.MD.B.3','tell and write time to the hour and half hour','Read 3:30 on an analog clock | The minute hand points to 6, which means 30 minutes. | The hour hand is halfway between 3 and 4. | The time is 3:30, or half past 3.','The minute hand points to 12 and the hour hand points to 6. What time is it? | 6:00','The minute hand points to 6 and the hour hand is between 4 and 5. What time is it? | 4:30','Draw clock hands to show 9:30. | 9:30'],
 '1-represent-and-interpret-data'=>['Represent and Interpret Data','Grade 1','1.MD.C.4','organize category data and answer questions about it','Make a fruit chart: 4 apples, 7 bananas, 5 oranges | Give each fruit a category. | Draw one mark for each vote. | Bananas have the most; there are 3 more bananas than apples.','A chart shows 3 cats and 6 dogs. Which has more? | dogs','A graph shows 5 red, 2 blue, and 4 green choices. How many choices altogether? | 11','Ask a class question, collect data, and make a picture graph. | Answers vary'],
 '2-measure-and-estimate-length'=>['Measure and Estimate Length','Grade 2','2.MD.A.1–4','estimate and measure lengths with standard units','Estimate and measure a book | Choose centimeters because the book is a small object. | Estimate 25 cm, then align the ruler at 0. | The measured length is 24 cm; the estimate was close.','Which unit is better for a pencil: centimeters or meters? | centimeters','A ribbon starts at 0 and ends at 18 on a centimeter ruler. How long is it? | 18 cm','Estimate and then measure a desk. Explain why your estimate is reasonable. | Answers vary'],
 '2-relate-addition-and-subtraction-to-length'=>['Relate Addition and Subtraction to Length','Grade 2','2.MD.B.5–6','solve length problems with addition, subtraction, and number lines','Join lengths of 34 cm and 28 cm | Draw a number line starting at 34. | Jump 20, then 8. | 34 + 28 = 62, so the total is 62 cm.','A 25 cm string and a 17 cm string are joined. What is the total length? | 42 cm','A board is 63 cm long. A 27 cm piece is cut off. How much remains? | 36 cm','Create a two-step length problem and solve it on a number line. | Answers vary'],
 '2-time-to-five-minutes'=>['Time to Five Minutes','Grade 2','2.MD.C.7','tell and write time to the nearest five minutes','Read 4:25 on an analog clock | Count by fives to the minute hand: 5, 10, 15, 20, 25. | The hour hand is just past 4. | The time is 4:25.','The minute hand points to 2 and the hour hand is just past 7. What time is it? | 7:10','What time is shown when the minute hand points to 5 and the hour hand is between 3 and 4? | 3:25','Draw hands for 8:45 and explain the hour-hand position. | 8:45'],
 '2-money'=>['Money','Grade 2','2.MD.C.8','identify coins and solve money problems','Find the value of 2 quarters and 3 dimes | Two quarters are 50 cents. | Three dimes are 30 cents. | 50 + 30 = 80 cents.','What is the value of 1 quarter and 2 dimes? | 45 cents','You have 3 quarters, 1 dime, and 2 pennies. How much money? | 87 cents','Show two different coin combinations worth 60 cents. | Answers vary'],
 '2-picture-and-bar-graphs'=>['Picture and Bar Graphs','Grade 2','2.MD.D.9–10','make and interpret picture graphs and bar graphs','Graph favorite fruit: apples 4, bananas 7, oranges 5 | Label the categories and scale. | Draw bars with heights 4, 7, and 5. | Bananas have 3 more votes than apples.','A bar graph shows 6 books and 3 games. How many more books? | 3','A picture graph uses one star for 2 votes. Four stars represent how many votes? | 8','Make a bar graph for three categories and write two questions about it. | Answers vary'],
 '3-time-mass-and-volume'=>['Time, Mass, and Volume','Grade 3','3.MD.A.1–2','solve elapsed-time, mass, and liquid-volume problems','Find elapsed time from 2:35 to 3:20 | Count 25 minutes to 3:00. | Count 20 more minutes to 3:20. | 25 + 20 = 45 minutes.','A movie starts at 1:15 and ends at 2:00. How long is it? | 45 minutes','A jug holds 3 liters and another holds 2 liters. How much altogether? | 5 liters','Write and solve a problem involving grams or liters. | Answers vary'],
 '3-area-and-perimeter'=>['Area and Perimeter','Grade 3','3.MD.C.5–8','measure area and perimeter of rectangles','Find area and perimeter of a 6-by-4 rectangle | Area counts square units: 6 × 4 = 24 square units. | Perimeter measures around: 6 + 4 + 6 + 4. | The perimeter is 20 units.','What is the area of a 5-by-3 rectangle? | 15 square units','What is the perimeter of an 8-by-2 rectangle? | 20 units','Draw two rectangles with area 24 but different perimeters. | Answers vary'],
 '3-scaled-graphs'=>['Scaled Graphs','Grade 3','3.MD.B.3','interpret picture and bar graphs with scales','Read a bar graph where each interval means 2 students | A bar at 4 intervals represents 4 groups of 2. | Multiply 4 × 2. | The bar represents 8 students.','A picture graph uses one symbol for 3 books. What do 4 symbols represent? | 12 books','A bar reaches 6 on a scale counting by 5. What value does it show? | 30','Create a scaled graph and explain its scale. | Answers vary'],
 '4-measurement-conversions'=>['Measurement Conversions','Grade 4','4.MD.A.1–3','convert measurements within one system and solve problems','Convert 3 feet to inches | One foot equals 12 inches. | Multiply 3 × 12. | 3 feet = 36 inches.','Convert 2 yards to feet. | 6 feet','Convert 5 pounds to ounces. | 80 ounces','Make a conversion table for one unit pair and describe the pattern. | Answers vary'],
 '5-convert-measurement-units'=>['Convert Measurement Units','Grade 5','5.MD.A.1','convert measurement units using multiplication and division','Convert 2.5 meters to centimeters | One meter equals 100 centimeters. | Multiply 2.5 × 100. | 2.5 meters = 250 centimeters.','Convert 3.2 kilograms to grams. | 3200 grams','Convert 4500 milliliters to liters. | 4.5 liters','Solve a multistep problem that requires two unit conversions. | Answers vary'],
 '5-volume'=>['Volume','Grade 5','5.MD.C.3–5','find volume of rectangular prisms with unit cubes and formulas','Find the volume of a 6-by-4-by-3 prism | Each layer has 6 × 4 = 24 cubes. | There are 3 layers. | V = 6 × 4 × 3 = 72 cubic units.','Find the volume of a 5-by-2-by-4 prism. | 40 cubic units','A prism has volume 60 cubic units, length 5, and width 3. What is its height? | 4 units','Design two prisms with volume 48 cubic units. | Answers vary'],
 '5-represent-and-interpret-data'=>['Represent and Interpret Data','Grade 5','5.MD.B.2','make and analyze line plots with fractional measurements','Plot 1/2, 3/4, 3/4, and 1 on a line plot | Mark the scale in fourths. | Place one X above 1/2, two above 3/4, and one above 1. | The most common measurement is 3/4.','A line plot has three X marks above 1/2. How many data values equal 1/2? | 3','Measurements are 1/4, 1/2, 1/2, and 3/4. What is their total? | 2','Create a fractional line plot and write a question that uses all the data. | Answers vary'],
];

$videos=['Measure Lengths'=>'https://www.youtube.com/watch?v=_irJM-um6HE','Measure and Estimate Length'=>'https://www.youtube.com/watch?v=0B91xPrwcPE','Picture and Bar Graphs'=>'https://www.youtube.com/watch?v=w49ddHSDGUA','Represent and Interpret Data'=>'https://www.youtube.com/watch?v=Oc1XmBVyXMk','Area and Perimeter'=>'https://www.youtube.com/watch?v=LoaBd-sPzkU','Volume'=>'https://www.youtube.com/watch?v=daCT_24RnIY','Convert Measurement Units'=>'https://www.youtube.com/watch?v=q9XCrpLPfGk'];
$default_video='https://www.youtube.com/watch?v=_irJM-um6HE';

$out=[];
foreach($lessons as $slug=>$v){
 [$title,$grade,$standard,$focus,$example,$warm,$guided,$independent]=$v;
 $practice=function($raw,$directions){[$q,$a]=array_map('trim',explode('|',$raw,2));return $directions.' || '.$q.' | '.$a.' | Identify the measurement, category, scale, or unit shown. Do not calculate yet. | Choose a matching model and label what each number means. | Use the labeled model, write an equation when needed, solve, include units, and check that the result fits the situation.';};
 $challenge=$practice(
  'Create a new measurement or data problem that asks you to '.$focus.'. Include a matching labeled model, solve it, and explain how you checked. | Answers vary',
  'Create your own measurement or data problem. Make the visual match the question, label every value and unit, solve, and explain your check.'
 );
 $out[$slug]=[
  'title'=>$title,'subtitle'=>'Use clear models, tools, and units to '.$focus.'.','essential_question'=>'How can a diagram, measuring tool, or data display help us '.$focus.'?',
  'learning_targets'=>"I can identify what is being measured or organized.\nI can choose and label a model that matches the situation.\nI can solve, include the correct unit, and explain why my answer makes sense.",
  'vocabulary'=>"measurement — a number and unit that describe an attribute\nunit — a fixed amount used to measure\nmodel — a picture, tool, or display that represents the situation\nscale — the value of each interval or symbol\nprecision — measuring and labeling carefully",
  'worked_examples'=>$example,
  'common_mistakes'=>"Starting a ruler away from zero | Align one endpoint with zero before reading the other endpoint.\nMixing units | Use one unit throughout or convert before calculating.\nIgnoring a graph scale | Read what each interval or symbol represents.\nGiving a number without a unit | Label centimeters, minutes, cents, square units, cubic units, or the correct category.",
  'real_life'=>'Measurement and data help us tell time, compare objects, use money, build spaces, follow recipes, read charts, and make decisions from information.',
  'videos'=>$title.' | '.($videos[$title]??$default_video),'video_chapters'=>"0:00 | Identify the quantity and unit\n1:00 | Build and label the visual model\n2:15 | Write the equation or read the data\n3:30 | Solve and check",
  'practice_warmup'=>$practice($warm,'Study the measurement or data display. Label the unit or scale, show your thinking, and enter the final answer.'),
  'guided_practice'=>$practice($guided,'Follow the steps. Build or read the matching visual, label every value and unit, write an equation when needed, and solve.'),
  'independent_practice'=>$practice($independent,'Choose the correct tool or display, show each step, include units, and enter your final answer.'),
  'challenge_practice'=>$challenge,
  'master_it'=>"I can select a model that matches the exact question.\nI can read or use a measurement unit and scale correctly.\nI can explain and check my result.",
  'mastery_questions'=>"What belongs with every measurement? | A unit ; A color ; A title only ; A guess | A\nWhat should you check before reading a graph? | Its scale and labels ; Its border color ; The longest word ; The page number | A\nWhy must a visual match the question? | It represents the same objects, quantities, and relationships ; It always makes the answer larger ; It removes the need for units ; It changes the data | A\nWhat makes an answer precise? | Clear labels, correct units, and careful measurement ; More decorations ; No explanation ; A larger number | A\nHow can you check a measurement result? | Compare it with the model, estimate, or inverse operation ; Erase the unit ; Change the scale ; Count unrelated objects | A",
  'parent_summary'=>'Students learn to measure, tell time, use money, read data displays, convert units, and reason about area, perimeter, and volume with accurate visual models.',
  'parent_conversation'=>"Ask: What is being measured or organized?\nAsk: What does each unit, mark, symbol, or interval mean?\nAsk: How does the picture prove the answer?",
  'parent_five_minute'=>'Choose a household object, clock, set of coins, or small data set. Have your child model it, label the unit or scale, solve one question, and explain a reasonableness check.',
  'teacher_objectives'=>"Students will choose measurement tools and data displays that match the task.\nStudents will calculate with grade-appropriate units, scales, and formulas.\nStudents will justify results using labeled visual evidence.",
  'teacher_pacing'=>"Launch | 5 minutes | Connect the quantity to a familiar context.\nLearn It | 10 minutes | Read a completed, labeled visual model.\nWorked Example | 8 minutes | Explain each measurement or data step.\nGuided Practice | 12 minutes | Release one labeled step at a time.\nIndependent Practice | 12 minutes | Require a model, result, and unit.\nMastery | 5 minutes | Check interpretation and transfer.",
  'teacher_misconceptions'=>"Students count marks instead of intervals | Trace the measured distance from zero to the endpoint.\nStudents ignore units or scales | Require units on every label and answer.\nStudents confuse area, perimeter, and volume | Connect each quantity to square units, boundary length, or cubic units.\nStudents use a generic picture | Compare every object and number in the visual with the prompt.",
  'teacher_differentiation'=>"Beginning | Use concrete rulers, clocks, coins, tiles, and cubes.\nDeveloping | Pair manipulatives with labeled diagrams.\nOn Level | Move among context, model, equation, and unit.\nAdvanced | Solve multistep conversions and data problems.\nMultilingual Learners | Pair unit vocabulary with objects, gestures, and visual labels.",
  'teacher_formative'=>"Check that the chosen visual matches the prompt exactly.\nAsk students to name the unit and scale before solving.\nListen for a clear connection between each number and the context.\nUse one estimate and one transfer problem as an exit check.",
  'standards'=>'CCSS.MATH.CONTENT.'.$standard.' — '.$grade.' Measurement & Data.\nStandards for Mathematical Practice: SMP 1, SMP 2, SMP 3, SMP 4, SMP 5, and SMP 6.'
 ];
}
return $out;
