<?php
if (!defined('ABSPATH')) exit;

/* Complete K–5 Number & Operations in Base Ten lesson set. */
$lessons = [
    'k-teen-numbers' => ['title'=>'Teen Numbers','grade'=>'Kindergarten','standard'=>'K.NBT.A.1','focus'=>'build each teen number as one ten and some ones','vocab'=>'ten — a group of 10; ones — single objects; teen number — a number from 11 through 19; compose — put parts together; numeral — a written number','example'=>'Build 14 with a ten and ones | Fill one ten-frame to show 10. | Place 4 more counters beside the full ten-frame. | One ten and 4 ones make 14: 10 + 4 = 14.','warm'=>'Show 12 as one ten and some ones. How many ones? | 2','guided'=>'Build 16 with one ten-frame and counters. How many extra counters are needed? | 6','independent'=>'Draw 18 as one ten and some ones. | 1 ten and 8 ones','challenge'=>'Explain why 19 is one less than two full tens.'],
    '1-counting-and-place-value-to-120' => ['title'=>'Counting and Place Value to 120','grade'=>'Grade 1','standard'=>'1.NBT.A.1, 1.NBT.B.2','focus'=>'count, read, and build numbers to 120 using tens and ones','vocab'=>'place value — the value a digit has because of its position; tens — groups of 10; ones — single units; digit — one symbol in a number; bundle — a group tied together','example'=>'Build 47 with tens and ones | Read the 4 in the tens place as 4 tens. | Read the 7 in the ones place as 7 ones. | Four tens and 7 ones equal 40 + 7 = 47.','warm'=>'What number has 3 tens and 6 ones? | 36','guided'=>'Build 82. How many tens and how many ones? | 8 tens and 2 ones','independent'=>'Write 95 in expanded form. | 90 + 5','challenge'=>'Find three numbers greater than 100 that have 1 in the hundreds place and 2 in another place.'],
    '1-compare-two-digit-numbers' => ['title'=>'Compare Two-Digit Numbers','grade'=>'Grade 1','standard'=>'1.NBT.B.3','focus'=>'compare two-digit numbers by looking at tens first, then ones','vocab'=>'compare — decide how two amounts are related; greater than — a larger value; less than — a smaller value; equal to — the same value; symbol — a mark such as >, <, or =','example'=>'Compare 47 and 42 | Compare the tens: both numbers have 4 tens. | Compare the ones: 7 ones is more than 2 ones. | Therefore 47 is greater than 42, so 47 > 42.','warm'=>'Which is greater: 36 or 63? | 63','guided'=>'Compare 58 and 55 using >, <, or =. | 58 > 55','independent'=>'Put 29, 92, and 49 in order from least to greatest. | 29, 49, 92','challenge'=>'Write two different two-digit numbers that have equal tens but differ by 6 ones.'],
    '1-add-within-100' => ['title'=>'Add Within 100','grade'=>'Grade 1','standard'=>'1.NBT.C.4, 1.NBT.C.5, 1.NBT.C.6','focus'=>'add within 100 by combining tens and ones','vocab'=>'addend — a number being added; sum — the answer to addition; compose — make a new unit; regroup — trade 10 ones for 1 ten; strategy — a helpful plan','example'=>'Add 36 + 27 with tens and ones | Add the ones: 6 + 7 = 13 ones. | Regroup 13 ones as 1 ten and 3 ones. | Add the tens: 3 + 2 + 1 = 6 tens, so the sum is 63.','warm'=>'Add 42 + 30. | 72','guided'=>'Use tens and ones to solve 48 + 25. | 73','independent'=>'Solve 67 + 18 and show the regrouping. | 85','challenge'=>'Find two addends with a sum of 100. Show two different solutions.'],
    '2-place-value-to-1000' => ['title'=>'Place Value to 1,000','grade'=>'Grade 2','standard'=>'2.NBT.A.1, 2.NBT.A.3','focus'=>'read, write, and build three-digit numbers with hundreds, tens, and ones','vocab'=>'hundred — 10 tens or 100 ones; standard form — a number written with digits; expanded form — a number written as place-value parts; word form — a number written with words; base-ten block — a model for place value','example'=>'Represent 326 three ways | The 3 shows 3 hundreds, the 2 shows 2 tens, and the 6 shows 6 ones. | Expanded form is 300 + 20 + 6. | Word form is three hundred twenty-six.','warm'=>'Write 4 hundreds, 7 tens, and 2 ones as a number. | 472','guided'=>'Write 605 in expanded form. | 600 + 5','independent'=>'Write eight hundred thirty-nine in standard form. | 839','challenge'=>'Write the greatest and least three-digit numbers you can make with 2, 5, and 8 once each.'],
    '2-compare-three-digit-numbers' => ['title'=>'Compare Three-Digit Numbers','grade'=>'Grade 2','standard'=>'2.NBT.A.4','focus'=>'compare three-digit numbers one place at a time','vocab'=>'hundreds place — the third place from the right; compare — decide which value is greater; greater than — larger; less than — smaller; equal to — the same value','example'=>'Compare 538 and 583 | Both numbers have 5 hundreds. | Compare the tens: 3 tens is less than 8 tens. | Therefore 538 < 583.','warm'=>'Which is greater: 704 or 740? | 740','guided'=>'Compare 629 and 629 using >, <, or =. | 629 = 629','independent'=>'Order 405, 450, and 540 from least to greatest. | 405, 450, 540','challenge'=>'Create two three-digit numbers that differ only in the tens place, then compare them.'],
    '2-add-and-subtract-within-1000' => ['title'=>'Add and Subtract Within 1,000','grade'=>'Grade 2','standard'=>'2.NBT.B.7, 2.NBT.B.9','focus'=>'add and subtract hundreds, tens, and ones with place-value strategies','vocab'=>'compose — trade smaller units for a larger unit; decompose — break a larger unit into smaller units; sum — addition answer; difference — subtraction answer; algorithm — ordered steps','example'=>'Add 368 + 257 by place value | Add ones: 8 + 7 = 15, so write 5 ones and regroup 1 ten. | Add tens: 6 + 5 + 1 = 12, so write 2 tens and regroup 1 hundred. | Add hundreds: 3 + 2 + 1 = 6, so the sum is 625.','warm'=>'Add 420 + 300. | 720','guided'=>'Solve 643 − 278 with regrouping. | 365','independent'=>'A library has 458 fiction books and 367 nonfiction books. How many books in all? | 825','challenge'=>'Estimate and then exactly solve 902 − 468. Explain whether the answer is reasonable.'],
    '3-rounding-and-multi-digit-arithmetic' => ['title'=>'Rounding and Multi-Digit Arithmetic','grade'=>'Grade 3','standard'=>'3.NBT.A.1, 3.NBT.A.2, 3.NBT.A.3','focus'=>'round numbers and use place value to calculate accurately','vocab'=>'round — replace a number with a nearby friendly number; benchmark — a nearby multiple of 10 or 100; estimate — a close answer; product — multiplication answer; reasonable — sensible for the problem','example'=>'Round 347 to the nearest hundred | Locate 347 between 300 and 400. | The halfway point is 350. Since 347 is below 350, it is closer to 300. | Therefore 347 rounds to 300.','warm'=>'Round 76 to the nearest ten. | 80','guided'=>'Use place value to add 468 + 257. | 725','independent'=>'Multiply 7 × 60. | 420','challenge'=>'Estimate 392 + 617, then find the exact sum and compare.'],
    '4-place-value-and-rounding' => ['title'=>'Place Value and Rounding','grade'=>'Grade 4','standard'=>'4.NBT.A.1, 4.NBT.A.2, 4.NBT.A.3','focus'=>'use place-value relationships to read, compare, and round large numbers','vocab'=>'period — a group of three digits; value — what a digit represents; ten times — 10 groups of an amount; round — find a nearby benchmark; expanded form — place-value parts','example'=>'Explain the two 5s in 55,000 | The first 5 is in the ten-thousands place and has a value of 50,000. | The second 5 is in the thousands place and has a value of 5,000. | A place to the left is worth 10 times as much: 50,000 = 10 × 5,000.','warm'=>'What is the value of 7 in 472,816? | 70,000','guided'=>'Round 386,492 to the nearest ten thousand. | 390,000','independent'=>'Write 604,070 in expanded form. | 600,000 + 4,000 + 70','challenge'=>'Write a six-digit number that rounds to 500,000 to the nearest hundred thousand and 540,000 to the nearest ten thousand.'],
    '4-multi-digit-addition-and-subtraction' => ['title'=>'Multi-Digit Addition and Subtraction','grade'=>'Grade 4','standard'=>'4.NBT.B.4','focus'=>'use the standard algorithm to add and subtract whole numbers','vocab'=>'standard algorithm — efficient agreed-upon calculation steps; regroup — compose or decompose a place-value unit; sum — addition result; difference — subtraction result; estimate — a close answer used to check','example'=>'Subtract 62,304 − 18,759 | Align digits by place value. | Regroup across places so each subtraction can be completed. | Subtract from right to left to get 43,545, then estimate to check.','warm'=>'Add 3,482 + 2,705. | 6,187','guided'=>'Subtract 8,004 − 2,768. | 5,236','independent'=>'Find 47,936 + 28,475. | 76,411','challenge'=>'Create an addition problem with a sum between 90,000 and 100,000 that requires regrouping in three places.'],
    '4-multi-digit-multiplication' => ['title'=>'Multi-Digit Multiplication','grade'=>'Grade 4','standard'=>'4.NBT.B.5','focus'=>'multiply whole numbers using place-value models and partial products','vocab'=>'factor — a number being multiplied; product — multiplication result; partial product — one part of a product; area model — a rectangle split to show multiplication; distributive property — multiply through parts','example'=>'Multiply 34 × 26 with partial products | Break 34 into 30 + 4 and 26 into 20 + 6. | Find 30×20=600, 30×6=180, 4×20=80, and 4×6=24. | Add the partial products: 600 + 180 + 80 + 24 = 884.','warm'=>'Multiply 7 × 43. | 301','guided'=>'Use an area model to solve 28 × 35. | 980','independent'=>'Find 146 × 7. | 1,022','challenge'=>'Explain why a zero placeholder is needed when using the standard algorithm for 42 × 36.'],
    '4-division-with-remainders' => ['title'=>'Division with Remainders','grade'=>'Grade 4','standard'=>'4.NBT.B.6','focus'=>'divide whole numbers and interpret remainders in context','vocab'=>'dividend — number being divided; divisor — number dividing; quotient — division result; remainder — amount left over; partial quotient — part of the quotient','example'=>'Divide 157 ÷ 6 | Use 20 groups of 6 to account for 120. | Use 6 more groups to account for 36, making 156. | The quotient is 26 with 1 left over: 157 ÷ 6 = 26 R1.','warm'=>'Find 84 ÷ 7. | 12','guided'=>'Solve 145 ÷ 8. | 18 R1','independent'=>'A teacher packs 194 pencils equally into boxes of 12. How many full boxes and how many pencils remain? | 16 boxes, 2 pencils remain','challenge'=>'Write two different story contexts for 53 ÷ 4 where the remainder is handled differently.'],
    '5-place-value-with-decimals' => ['title'=>'Place Value with Decimals','grade'=>'Grade 5','standard'=>'5.NBT.A.1, 5.NBT.A.3, 5.NBT.A.4','focus'=>'read, compare, and round decimals through thousandths','vocab'=>'decimal — a number with a whole-number part and fractional part; tenths — one of 10 equal parts; hundredths — one of 100 equal parts; thousandths — one of 1,000 equal parts; decimal point — separates whole units from fractional units','example'=>'Compare 4.307 and 4.37 | Align the decimal points and compare equal places. | Both have 4 ones and 3 tenths. Compare hundredths: 0 hundredths is less than 7 hundredths. | Therefore 4.307 < 4.370.','warm'=>'Write six and forty-two hundredths as a decimal. | 6.42','guided'=>'Round 8.746 to the nearest tenth. | 8.7','independent'=>'Order 0.58, 0.508, and 0.85 from least to greatest. | 0.508, 0.58, 0.85','challenge'=>'Write three different decimals that round to 5.24 to the nearest hundredth.'],
    '5-multi-digit-multiplication-and-division' => ['title'=>'Multi-Digit Multiplication and Division','grade'=>'Grade 5','standard'=>'5.NBT.B.5, 5.NBT.B.6','focus'=>'multiply and divide multi-digit whole numbers efficiently','vocab'=>'standard algorithm — efficient calculation steps; partial product — one multiplication part; partial quotient — one division part; dividend — number divided; divisor — number dividing','example'=>'Divide 2,856 ÷ 24 with partial quotients | Use 100 groups of 24 to account for 2,400, leaving 456. | Use 19 more groups of 24 to account for 456. | Add the partial quotients: 100 + 19 = 119.','warm'=>'Multiply 286 × 34. | 9,724','guided'=>'Use partial quotients to solve 1,764 ÷ 21. | 84','independent'=>'Find 4,208 × 57. | 239,856','challenge'=>'Estimate and exactly solve 7,425 ÷ 33. Explain how the estimate checks the quotient.'],
    '5-decimal-operations' => ['title'=>'Decimal Operations','grade'=>'Grade 5','standard'=>'5.NBT.B.7','focus'=>'add, subtract, multiply, and divide decimals using place-value reasoning','vocab'=>'decimal point — separates whole and fractional places; equivalent decimal — same value written with different zeros; product — multiplication answer; quotient — division answer; place-value model — a representation of units, tenths, and hundredths','example'=>'Add 3.48 + 2.7 | Write 2.7 as 2.70 so equal places line up. | Add hundredths, tenths, and ones by place value. | The sum is 6.18.','warm'=>'Subtract 9.5 − 3.27. | 6.23','guided'=>'Use a model or place value to multiply 2.4 × 3. | 7.2','independent'=>'Divide 8.4 ÷ 4. | 2.1','challenge'=>'Create a shopping problem that uses two decimal operations and has a final answer of $12.50.'],
];

$expand = function($item) {
    $title=$item['title']; $grade=$item['grade']; $focus=$item['focus'];
    $practice=function($raw,$directions){ list($question,$answer)=array_map('trim',explode('|',$raw,2)); return $directions.' || '.$question.' | '.$answer.' | Build or sketch the place-value model before calculating. | Work one place at a time and label every regrouping or comparison. | Use the lesson model, calculate carefully, and estimate or use the inverse operation to check.'; };
    return [
        'title'=>$title,
        'subtitle'=>'Use place-value ideas and visual models to '.$focus.'.',
        'essential_question'=>'How can place value and a clear model help us '.$focus.'?',
        'learning_targets'=>"I can name the value of each digit.\nI can choose a place-value model or strategy that fits the problem.\nI can solve and check my answer.",
        'vocabulary'=>str_replace('; ',"\n",$item['vocab']),
        'worked_examples'=>$item['example'],
        'common_mistakes'=>"Reading a digit without naming its place | Say both the digit and its value.\nMisaligning places | Line up equal place values, especially decimal points.\nRegrouping without explaining the trade | State which 10 smaller units become 1 larger unit.\nSkipping a reasonableness check | Estimate before or after calculating.",
        'real_life'=>'Base-ten reasoning helps us read prices, measure distances, compare populations, estimate costs, and calculate accurately with whole numbers and decimals.',
        'videos'=>$title.' | https://www.khanacademy.org/math/cc-'.(stripos($grade,'Kindergarten')!==false?'kindergarten':strtolower(str_replace(' ','-',$grade))).'-math',
        'video_chapters'=>"0:00 | Read the number or problem\n1:00 | Build the place-value model\n2:15 | Choose a strategy\n3:30 | Solve and check",
        'practice_warmup'=>$practice($item['warm'],'Use a quick place-value model. Label what each digit or quantity means.'),
        'guided_practice'=>$practice($item['guided'],'Follow each step. Build or draw the model, write the calculation, and explain each place-value move.'),
        'independent_practice'=>$practice($item['independent'],'Choose a model or algorithm, show your work, and enter your final answer.'),
        'challenge_practice'=>$item['challenge'],
        'master_it'=>"I can explain the value of a digit using correct vocabulary.\nI can use a model and an efficient calculation strategy.\nI can check whether my answer is reasonable.",
        'mastery_questions'=>"Why must digits be aligned when adding? | To make the writing pretty ; To combine equal place values ; To make every number longer ; To avoid regrouping | B\nWhat does regrouping mean? | Rename equal value using different place-value units ; Change the answer ; Round every number ; Move the decimal randomly | A\nWhich check is useful after calculating? | Estimate the expected size ; Ignore the units ; Change an addend ; Read only the last digit | A\nA digit one place to the left is how many times the value? | 2 ; 5 ; 10 ; 100 | C\nWhy use a visual model? | It shows the place-value relationship ; It removes all numbers ; It gives every answer ; It replaces explaining | A",
        'parent_summary'=>'Students use objects, drawings, number lines, place-value charts, and algorithms to understand how our base-ten number system works. Explanations and estimation are emphasized along with accuracy.',
        'parent_conversation'=>"Ask: What is the value of each digit?\nAsk: What trade or regrouping happened?\nAsk: What estimate tells you the answer makes sense?",
        'parent_five_minute'=>'Choose a number from a receipt, address, or measurement. Ask your child to read it, write it in expanded form, compare it with another number, and explain the value of one digit.',
        'teacher_objectives'=>"Students will represent numbers and operations with grade-appropriate base-ten models.\nStudents will calculate accurately with place-value reasoning.\nStudents will explain and check their strategy using precise vocabulary.",
        'teacher_pacing'=>"Launch | 5 minutes | Connect to a familiar number or measurement.\nLearn It | 10 minutes | Model the place-value relationship visually.\nWorked Example | 8 minutes | Explain each place-value decision.\nGuided Practice | 12 minutes | Release one step at a time.\nIndependent Practice | 12 minutes | Require a model or labeled algorithm.\nMastery | 5 minutes | Check accuracy, vocabulary, and reasoning.",
        'teacher_misconceptions'=>"Students name the digit instead of its value | Ask for the digit, place, and value separately.\nStudents compare by number length or last digit | Compare from the greatest place first.\nStudents regroup procedurally without understanding | Model every trade with base-ten units.\nStudents misalign decimals | Use a place-value chart and equivalent trailing zeros.",
        'teacher_differentiation'=>"Beginning | Use concrete base-ten blocks and smaller numbers.\nDeveloping | Connect blocks to drawings and expanded form.\nOn Level | Move among models, algorithms, and explanations.\nAdvanced | Compare methods and justify general place-value rules.\nMultilingual Learners | Pair vocabulary with labeled visual models and sentence frames.",
        'teacher_formative'=>"Ask students to identify a digit, its place, and its value.\nCheck whether the visual model matches the written number or calculation.\nListen for an explanation of every regrouping.\nUse an estimate and one transfer problem as an exit check.",
        'standards'=>'CCSS.MATH.CONTENT.'.$item['standard'].' — '.$grade.' Number & Operations in Base Ten.\nStandards for Mathematical Practice: SMP 1, SMP 2, SMP 3, SMP 4, SMP 6, and SMP 7.'
    ];
};

return array_map($expand,$lessons);
