<?php
if (!defined('ABSPATH')) exit;

/*
 * Complete K–5 Operations & Algebraic Thinking lesson set.
 * Each compact record is expanded into the full MathBinder Gold lesson schema.
 */
$lessons = [
    'k-compose-and-decompose-numbers' => [
        'title'=>'Compose and Decompose Numbers','grade'=>'Kindergarten','standard'=>'K.OA.A.3','focus'=>'put numbers together and take them apart in more than one way','vocab'=>'compose — put parts together to make a whole; decompose — break a whole into parts; part — one amount in a whole; whole — the total amount','example'=>'Make 7 with two parts | Start with 7 counters. | Put 5 counters in one group and 2 in another. | The parts 5 and 2 make the whole 7, so 5 + 2 = 7.','warm'=>'Show 6 as 4 and another part. What is the missing part? | 2','guided'=>'There are 8 apples. Put 3 in one basket. How many go in the other basket? | 5','independent'=>'Write two parts that make 9. | 4 and 5','challenge'=>'Find every pair of whole-number parts that makes 10. Explain how you know your list is complete.'
    ],
    'k-addition-within-10' => [
        'title'=>'Addition Within 10','grade'=>'Kindergarten','standard'=>'K.OA.A.1, K.OA.A.2, K.OA.A.5','focus'=>'join two groups and find how many there are altogether','vocab'=>'add — join amounts; plus sign — shows addition; equal sign — means the same amount as; sum — the total after adding; altogether — in all','example'=>'Add 3 stars and 2 stars | Draw a group of 3 stars. | Draw 2 more stars beside them. | Count all the stars: 1, 2, 3, 4, 5, so 3 + 2 = 5.','warm'=>'There are 2 birds. 3 more birds join them. How many birds are there altogether? | 5','guided'=>'Mia has 4 crayons and gets 2 more. How many crayons does she have now? | 6','independent'=>'Draw a picture and solve 5 + 3. | 8','challenge'=>'Write three different addition equations that have a sum of 10.'
    ],
    'k-subtraction-within-10' => [
        'title'=>'Subtraction Within 10','grade'=>'Kindergarten','standard'=>'K.OA.A.1, K.OA.A.2, K.OA.A.5','focus'=>'take away from a group and find how many remain','vocab'=>'subtract — take away or find a difference; minus sign — shows subtraction; difference — the answer to subtraction; remain — are left; take away — remove from a group','example'=>'Take 2 stars away from 6 stars | Draw 6 stars. | Cross out 2 stars to show they leave. | Count the 4 stars that remain, so 6 − 2 = 4.','warm'=>'There are 7 balloons. 2 fly away. How many balloons remain? | 5','guided'=>'A plate has 9 crackers. Sam eats 3. How many crackers are left? | 6','independent'=>'Draw a picture and solve 8 − 5. | 3','challenge'=>'Write two different subtraction equations that have a difference of 4.'
    ],
    '1-addition-and-subtraction-stories' => [
        'title'=>'Addition and Subtraction Stories','grade'=>'Grade 1','standard'=>'1.OA.A.1, 1.OA.A.2','focus'=>'choose addition or subtraction to solve a story problem','vocab'=>'join — put groups together; separate — take part away; compare — tell how amounts are different; equation — a number sentence with an equal sign; unknown — the number we need to find','example'=>'Solve a joining story | Ava has 5 pencils and gets 4 more. | The word more tells us the group grows, so add 5 + 4. | Count on four numbers from 5 to get 9 pencils.','warm'=>'Leo has 6 toy cars and gets 3 more. How many cars does he have? | 9','guided'=>'There are 12 ducks. 5 swim away. How many ducks remain? | 7','independent'=>'Nina has 8 stickers. Omar has 3 fewer. How many stickers does Omar have? | 5','challenge'=>'Write one joining story and one separating story that both use the numbers 6, 4, and 10.'
    ],
    '1-properties-of-addition' => [
        'title'=>'Properties of Addition','grade'=>'Grade 1','standard'=>'1.OA.B.3, 1.OA.B.4','focus'=>'use addition properties to make problems easier','vocab'=>'commutative property — addends can switch order; associative property — addends can be grouped differently; identity property — adding zero keeps a number the same; addend — a number being added; related facts — equations using the same numbers','example'=>'Switch the addends | Build 3 + 5 with counters. | Switch the groups to show 5 + 3. | Both arrangements have 8 counters, so 3 + 5 = 5 + 3.','warm'=>'Use the commutative property: 2 + 7 = 7 + __. | 2','guided'=>'Which is easier to add first in 2 + 8 + 3? | 2 and 8','independent'=>'What number makes 9 + 0 = __ true? | 9','challenge'=>'Use addition properties to find 6 + 7 + 4 mentally. Explain your grouping.'
    ],
    '1-addition-and-subtraction-within-20' => [
        'title'=>'Addition and Subtraction Within 20','grade'=>'Grade 1','standard'=>'1.OA.C.6','focus'=>'use efficient strategies to add and subtract within 20','vocab'=>'count on — begin at a number and count forward; make ten — create a group of ten first; doubles — two equal addends; fact family — related addition and subtraction facts; strategy — a helpful plan','example'=>'Make ten to solve 8 + 5 | Break 5 into 2 and 3. | Add 8 + 2 to make 10. | Add the remaining 3: 10 + 3 = 13.','warm'=>'Use make ten to solve 9 + 4. | 13','guided'=>'Use a doubles fact to solve 7 + 8. | 15','independent'=>'Solve 16 − 7 and show a strategy. | 9','challenge'=>'Find two different strategies for 14 − 8 and explain why both work.'
    ],
    '1-unknowns-in-equations' => [
        'title'=>'Unknowns in Equations','grade'=>'Grade 1','standard'=>'1.OA.D.7, 1.OA.D.8','focus'=>'find a missing number in any position of an equation','vocab'=>'unknown — a missing number; equation — two equal amounts; true — mathematically correct; equal sign — shows both sides have the same value; inverse operations — operations that undo each other','example'=>'Find the missing addend in 6 + □ = 10 | Ask what number joins 6 to make 10. | Count on from 6: 7, 8, 9, 10. | Four counts are needed, so the unknown is 4.','warm'=>'Find the unknown: 5 + □ = 9. | 4','guided'=>'Find the unknown: □ − 3 = 7. | 10','independent'=>'Is 8 = 5 + 3 true or false? | true','challenge'=>'Write three different equations with the unknown in three different positions and an answer of 6.'
    ],
    '2-addition-and-subtraction-within-100' => [
        'title'=>'Addition and Subtraction Within 100','grade'=>'Grade 2','standard'=>'2.OA.A.1, 2.OA.B.2','focus'=>'add and subtract within 100 using place-value and mental strategies','vocab'=>'tens — groups of ten; ones — single units; compose — make a new ten; decompose — break apart a ten; mental strategy — a way to solve without a written algorithm','example'=>'Add 38 + 24 by place value | Break 38 into 30 + 8 and 24 into 20 + 4. | Add tens: 30 + 20 = 50. Add ones: 8 + 4 = 12. | Combine 50 + 12 to get 62.','warm'=>'Add 46 + 30. | 76','guided'=>'Solve 72 − 28 by breaking apart tens and ones. | 44','independent'=>'A class collected 37 cans on Monday and 45 on Tuesday. How many cans in all? | 82','challenge'=>'Find two ways to solve 63 − 29. Compare the strategies.'
    ],
    '2-equal-groups-and-arrays' => [
        'title'=>'Equal Groups and Arrays','grade'=>'Grade 2','standard'=>'2.OA.C.3, 2.OA.C.4','focus'=>'organize objects into equal groups, rows, and columns','vocab'=>'equal groups — groups with the same number; array — objects in equal rows and columns; row — objects across; column — objects up and down; repeated addition — adding the same number again and again','example'=>'Build 3 rows of 4 stars | Draw 4 stars in the first row. | Make 2 more rows with 4 stars in each row. | Add 4 + 4 + 4 to find 12 stars.','warm'=>'An array has 2 rows of 5 dots. How many dots are there? | 10','guided'=>'Draw 4 equal groups with 3 blocks in each group. How many blocks? | 12','independent'=>'Write repeated addition for 5 rows of 2 stars. | 2 + 2 + 2 + 2 + 2 = 10','challenge'=>'Show 18 objects in two different arrays. Name the rows and columns in each.'
    ],
    '3-meaning-of-multiplication' => [
        'title'=>'Meaning of Multiplication','grade'=>'Grade 3','standard'=>'3.OA.A.1, 3.OA.A.3','focus'=>'understand multiplication as equal groups','vocab'=>'multiply — find the total in equal groups; factor — a number being multiplied; product — the answer to multiplication; equal groups — groups with the same amount; array — equal rows and columns','example'=>'Find 4 groups of 6 | Draw 4 circles to stand for the groups. | Put 6 dots in each circle. | Add 6 + 6 + 6 + 6 = 24, so 4 × 6 = 24.','warm'=>'There are 3 bags with 5 apples in each bag. How many apples are there? | 15','guided'=>'A theater has 6 rows with 4 seats in each row. How many seats? | 24','independent'=>'Draw an array to show 7 × 3. What is the product? | 21','challenge'=>'Write two different equal-group stories for 5 × 8.'
    ],
    '3-meaning-of-division' => [
        'title'=>'Meaning of Division','grade'=>'Grade 3','standard'=>'3.OA.A.2, 3.OA.A.3','focus'=>'understand division as sharing or making equal groups','vocab'=>'divide — separate into equal groups; dividend — the amount being divided; divisor — the number of groups or group size; quotient — the answer to division; share equally — give the same amount to each group','example'=>'Share 18 stars among 3 students | Draw 3 circles for the students. | Give one star to each circle until all 18 are shared. | Each circle has 6 stars, so 18 ÷ 3 = 6.','warm'=>'Share 12 crackers equally among 4 children. How many crackers does each child get? | 3','guided'=>'Put 20 blocks into groups of 5. How many groups can you make? | 4','independent'=>'Draw a model for 24 ÷ 6. What is the quotient? | 4','challenge'=>'Explain the difference between 24 ÷ 6 and 24 ÷ 4 using group models.'
    ],
    '3-multiplication-and-division-facts' => [
        'title'=>'Multiplication and Division Facts','grade'=>'Grade 3','standard'=>'3.OA.B.5, 3.OA.B.6, 3.OA.C.7','focus'=>'use patterns and related facts to multiply and divide within 100','vocab'=>'fact family — related multiplication and division equations; inverse operations — operations that undo each other; product — multiplication answer; quotient — division answer; fluent — accurate and efficient','example'=>'Use a known fact to solve 7 × 6 | Start with the known fact 5 × 6 = 30. | Add 2 more groups of 6: 30 + 12. | The product is 42.','warm'=>'Use a related multiplication fact to solve 35 ÷ 5. | 7','guided'=>'If 8 × 4 = 32, what is 32 ÷ 8? | 4','independent'=>'Find 9 × 7 and name a strategy. | 63','challenge'=>'Create a fact family using 8, 9, and 72. Explain how each equation is related.'
    ],
    '3-properties-and-patterns' => [
        'title'=>'Properties and Patterns','grade'=>'Grade 3','standard'=>'3.OA.B.5, 3.OA.D.9','focus'=>'use properties and patterns to solve multiplication problems','vocab'=>'distributive property — break a factor into parts; commutative property — factors can switch order; associative property — factors can be grouped differently; pattern — a rule that repeats or grows; multiple — a product of a number and a whole number','example'=>'Break apart 7 × 8 | Split 7 into 5 + 2. | Find 5 × 8 = 40 and 2 × 8 = 16. | Add the parts: 40 + 16 = 56.','warm'=>'Use the commutative property: 4 × 9 = 9 × __. | 4','guided'=>'Use the distributive property to solve 6 × 7 as 5 × 7 plus one more group of 7. | 42','independent'=>'What pattern do you notice in the products of 5? | They end in 0 or 5','challenge'=>'Use two different break-apart strategies to solve 9 × 8.'
    ],
    '3-multi-step-word-problems' => [
        'title'=>'Multi-Step Word Problems','grade'=>'Grade 3','standard'=>'3.OA.D.8','focus'=>'solve problems that need more than one operation','vocab'=>'multi-step — needing two or more steps; operation — addition, subtraction, multiplication, or division; estimate — a close answer; equation — a statement that two amounts are equal; reasonableness — whether an answer makes sense','example'=>'Solve a two-step classroom story | There are 4 tables with 6 students at each table. Then 3 students leave. | First multiply 4 × 6 = 24 students. | Then subtract 24 − 3 = 21 students remaining.','warm'=>'There are 3 boxes with 8 markers each. 5 markers are used. How many remain? | 19','guided'=>'Four teams collect 7 cans each, then collect 6 more cans. How many cans total? | 34','independent'=>'A teacher has 30 pencils and shares them among 5 tables. Then each table gets 2 more. How many pencils does each table have? | 8','challenge'=>'Write a two-step story with an answer of 25 and solve it with equations.'
    ],
    '4-factors-and-multiples' => [
        'title'=>'Factors and Multiples','grade'=>'Grade 4','standard'=>'4.OA.B.4','focus'=>'find factor pairs, multiples, prime numbers, and composite numbers','vocab'=>'factor — a whole number that divides evenly into another; multiple — a product of a number and a whole number; factor pair — two factors whose product is a number; prime — exactly two factors; composite — more than two factors','example'=>'Find all factor pairs of 24 | Start with 1 × 24. | Test whole numbers in order: 2 × 12, 3 × 8, and 4 × 6. | The factor pairs are 1 and 24, 2 and 12, 3 and 8, and 4 and 6.','warm'=>'List the first five multiples of 6. | 6, 12, 18, 24, 30','guided'=>'Find all factor pairs of 18. | 1 and 18, 2 and 9, 3 and 6','independent'=>'Is 29 prime or composite? | prime','challenge'=>'Find a number less than 50 with exactly six factors. List the factors.'
    ],
    '4-number-and-shape-patterns' => [
        'title'=>'Number and Shape Patterns','grade'=>'Grade 4','standard'=>'4.OA.C.5','focus'=>'generate and explain number or shape patterns using a rule','vocab'=>'pattern — an ordered set that follows a rule; rule — directions for making the next term; term — one item in a pattern; sequence — terms in order; feature — a quality such as even, odd, color, or shape','example'=>'Use the rule add 4, starting at 3 | The first term is 3. | Add 4 to get 7, then 11, then 15. | The pattern is 3, 7, 11, 15, 19.','warm'=>'Start at 2 and multiply by 3 each time. What are the next three terms? | 6, 18, 54','guided'=>'A shape pattern repeats square, triangle, circle. What is the 8th shape? | triangle','independent'=>'Generate five terms for the rule add 6, starting at 5. | 5, 11, 17, 23, 29','challenge'=>'Create a pattern with one stated rule and one hidden feature. Explain both.'
    ],
    '5-numerical-expressions-and-patterns' => [
        'title'=>'Numerical Expressions and Patterns','grade'=>'Grade 5','standard'=>'5.OA.A.1, 5.OA.A.2, 5.OA.B.3','focus'=>'write, evaluate, and compare numerical expressions and related patterns','vocab'=>'numerical expression — numbers and operation symbols without an equal sign; parentheses — symbols showing what to do first; evaluate — find the value; coordinate pair — two numbers locating a point; corresponding terms — terms in the same position in two patterns','example'=>'Evaluate 4 × (7 − 2) + 3 | Work inside parentheses first: 7 − 2 = 5. | Multiply next: 4 × 5 = 20. | Add 3 to get 23.','warm'=>'Evaluate 6 + 3 × 4. | 18','guided'=>'Write an expression for add 8 and 5, then multiply by 2. | (8 + 5) × 2','independent'=>'Pattern A starts at 0 and adds 3. Pattern B starts at 0 and adds 6. Compare the fifth terms. | 12 and 24','challenge'=>'Create two related patterns whose corresponding terms differ by a growing amount. Explain the relationship.'
    ],
];

$expand = function($item) {
    $title = $item['title']; $grade = $item['grade']; $focus = $item['focus'];
    $practice = function($raw, $directions) {
        list($question, $answer) = array_map('trim', explode('|', $raw, 2));
        return $directions . ' || ' . $question . ' | ' . $answer
            . ' | Choose a model and label what each number means before calculating.'
            . ' | Show one small step at a time and check that the operation matches the story or equation.'
            . ' | Use the lesson model, complete the calculation, and check that the result answers the question.';
    };
    return [
        'title'=>$title,
        'subtitle'=>'Build strong operations and algebraic thinking by learning to ' . $focus . '.',
        'essential_question'=>'How can a picture, equation, or pattern help us ' . $focus . '?',
        'learning_targets'=>"I can explain what the numbers and symbols mean.\nI can choose a picture, object model, equation, or pattern that fits the problem.\nI can solve and check my answer.",
        'vocabulary'=>str_replace('; ', "\n", $item['vocab']),
        'worked_examples'=>$item['example'],
        'common_mistakes'=>"Choosing an operation from one keyword | Read the whole situation and decide what happens to the amount.\nWriting an answer without a model or equation | Show a picture, objects, or a number sentence that matches.\nStopping without checking | Use the inverse operation, recount, or substitute the answer to check.",
        'real_life'=>'Operations and algebraic thinking help us share objects, compare choices, count groups, find missing amounts, and describe patterns in everyday situations.',
        'videos'=>$title . ' | https://www.khanacademy.org/math/cc-' . (stripos($grade, 'Kindergarten') !== false ? 'kindergarten' : strtolower(str_replace(' ', '-', $grade))) . '-math',
        'video_chapters'=>"0:00 | Understand the problem\n1:00 | Build or draw a model\n2:15 | Write the equation or rule\n3:15 | Solve and check",
        'practice_warmup'=>$practice($item['warm'], 'Use a quick picture or equation. Explain what the numbers mean.'),
        'guided_practice'=>$practice($item['guided'], 'Follow the steps. Build or draw the situation, write an equation, and solve.'),
        'independent_practice'=>$practice($item['independent'], 'Choose a model, show your work, and enter your final answer.'),
        'challenge_practice'=>$item['challenge'],
        'master_it'=>"I can choose an operation or rule that matches the problem.\nI can use correct mathematical vocabulary to explain my model.\nI can check whether my answer is reasonable.",
        'mastery_questions'=>"Which action helps you understand a problem first? | Guess the answer ; Identify what each number means ; Ignore the question ; Choose the largest number | B\nWhat does an equal sign mean? | Add next ; The left side is larger ; Both sides have the same value ; Stop working | C\nWhich is a good way to check an answer? | Use a related or inverse operation ; Change the question ; Erase the model ; Pick a new number | A\nWhy should a model match the question? | To make it colorful ; To show the mathematical relationship ; To avoid numbers ; To make every answer the same | B\nWhat should a final answer include in a story problem? | Only a symbol ; A number that answers the question, with units when needed ; Every number from the story ; A new question | B",
        'parent_summary'=>'Students learn to represent operations and patterns with objects, drawings, equations, and clear mathematical language. The lesson emphasizes understanding before memorizing a procedure.',
        'parent_conversation'=>"Ask: What is happening to the amount in this problem?\nAsk: Which picture or equation matches, and why?\nAsk: How can you check your answer another way?",
        'parent_five_minute'=>'Use small household objects to act out one lesson problem. Ask your child to draw the model, write the matching equation or rule, and explain how the model proves the answer.',
        'teacher_objectives'=>"Students will represent the lesson concept with concrete objects, drawings, and symbols.\nStudents will solve grade-appropriate problems accurately.\nStudents will explain and check their reasoning using precise vocabulary.",
        'teacher_pacing'=>"Launch | 5 minutes | Connect to a familiar situation.\nLearn It | 10 minutes | Model the concept with objects and pictures.\nWorked Example | 7 minutes | Explain why each step works.\nGuided Practice | 12 minutes | Release one step at a time.\nIndependent Practice | 12 minutes | Require a model and an answer.\nMastery | 5 minutes | Check understanding and vocabulary.",
        'teacher_misconceptions'=>"Students act on a keyword instead of the full situation | Have students retell what changes before choosing an operation.\nStudents treat the equal sign as an answer signal | Use true equations in different forms and describe balance.\nStudents calculate correctly but cannot explain | Require a labeled model and a sentence connecting it to the equation.",
        'teacher_differentiation'=>"Beginning | Use concrete objects and smaller numbers.\nDeveloping | Pair objects with a drawing and equation.\nOn Level | Move flexibly among models, equations, and words.\nAdvanced | Compare strategies, create problems, and justify general rules.\nMultilingual Learners | Preteach vocabulary with pictures, gestures, and sentence frames.",
        'teacher_formative'=>"Listen for an explanation of what each number means.\nCheck whether the model matches the operation or pattern.\nAsk students to estimate or predict before solving.\nUse one transfer problem with different numbers as an exit check.",
        'standards'=>'CCSS.MATH.CONTENT.' . $item['standard'] . ' — ' . $grade . ' Operations & Algebraic Thinking.\nStandards for Mathematical Practice: SMP 1, SMP 2, SMP 3, SMP 4, and SMP 6.'
    ];
};

return array_map($expand, $lessons);
